/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: ac42ac9a52da7aa14cff67099b8507ea)
interface __BaseEnv_Env {
	RELAY_NODES: DurableObjectNamespace<import("./index").RelayNode>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RelayNode";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
