/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 5d141c11d1ce1beb4702dcbd0505beb3)
interface __BaseEnv_Env {
	BUZZ_REQUIRE_AUTH: "";
	BUZZ_REPLICATION_PEERS: "";
	RELAY_NODES: DurableObjectNamespace<import("./index").RelayNode>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RelayNode";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
