/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 02cc135435db8a801f97756d5cefffcf)
interface __BaseEnv_Env {
	BUZZ_REQUIRE_AUTH: "";
	RELAY_NODES: DurableObjectNamespace<import("./index").RelayNode>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RelayNode";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
