use crate::managed_agents::KnownAcpRuntime;

pub(super) fn known_runtime_fixture() -> KnownAcpRuntime {
    KnownAcpRuntime {
        id: "test-runtime",
        label: "Test runtime",
        display_label: "Test runtime",
        sort_priority: 100,
        onboarding_visible: false,
        commands: &[],
        aliases: &[],
        default_args: &[],
        default_parallelism: None,
        defer_agent_start_until_work: true,
        default_idle_timeout_secs: None,
        icon_url: "",
        icon_scale: 1.0,
        avatar_url: "",
        superseded_avatar_urls: &[],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: None,
        cli_install_commands: &[],
        cli_install_commands_windows: &[],
        adapter_install_commands: &[],
        cli_install_instructions_url: "",
        adapter_install_instructions_url: "",
        cli_install_hint: "",
        adapter_install_hint: "",
        skill_dir: None,
        supports_acp_model_switching: false,
        accepts_harness_model: true,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        enforced_env: &[],
        scrub_env_vars: &[],
        config_file_path: None,
        config_file_format: None,
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: None,
        auth_probe_args: None,
        auth_login_args: None,
    }
}
