import { readFileSync, writeFileSync } from "node:fs";
import { COMPACT_FOUNDATIONS, FOUNDATION_GROUPS } from "./src/foundations.ts";
const declarations = FOUNDATION_GROUPS.flatMap((g) =>
  g.roles.map(([name, value]) => "  --" + name + ": " + value + ";"),
).join("\n");
const compact = Object.entries(COMPACT_FOUNDATIONS)
  .map(([name, value]) => `  --${name}: ${value};`)
  .join("\n");
const css =
  "/* Generated by packages/design-tokens/build.mjs. */\n@theme {\n" +
  declarations +
  '\n}\n:root[data-density="compact"] {\n' +
  compact +
  "\n}\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --duration-state: 0ms;\n    --duration-enter: 0ms;\n    --duration-exit: 0ms;\n    --press-scale: 1;\n  }\n}\n";
const path = new URL("./src/foundations.css", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8") !== css)
    throw new Error("Foundation CSS is stale: run pnpm tokens:build");
} else writeFileSync(path, css);
