import type {
  MissionConstraint,
  PlanningProject,
  PlanningTask,
} from "./contracts";

export const planningProject: PlanningProject = {
  schemaVersion: 1,
  id: "deployment-1",
  title: "Regional logistics deployment",
  purpose: "Sustain the assigned task group",
  missionReadyDate: "2026-08-10",
  status: "active",
  progressPercent: 25,
  owner: "Operations Officer",
  linkedActivityIds: ["fas-activity-1"],
  assumptions: ["Port services remain available"],
  createdAt: "2026-07-29T00:00:00Z",
  updatedAt: "2026-07-29T00:00:00Z",
};
export const planningTask: PlanningTask = {
  schemaVersion: 1,
  id: "task-a",
  projectId: "deployment-1",
  wbs: "1.1",
  parentTaskId: null,
  title: "Prepare logistics support plan",
  owner: "Logistics Officer",
  status: "inProgress",
  percentComplete: 20,
  plannedStart: "2026-08-03",
  dueDate: "2026-08-04",
  durationWorkdays: 2,
  dependencyIds: [],
  fixedStart: null,
  linkedCapabilityId: "replenishment-at-sea",
  linkedMissionRequirementId: "sustain-task-group",
  notes: null,
  sourceEvidence: "Workbook row 4",
  isSummary: false,
  createdAt: "2026-07-29T00:00:00Z",
  updatedAt: "2026-07-29T00:00:00Z",
};
export const missionConstraint: MissionConstraint = {
  schemaVersion: 1,
  id: "constraint-1",
  projectId: "deployment-1",
  type: "defect",
  description: "Port seaboat davit unserviceable",
  owner: "Marine Engineer Officer",
  severity: "critical",
  status: "open",
  linkedMissionRequirementId: "conduct-seaboat-operations",
  linkedCapabilityId: "seaboat-capability",
  linkedTaskId: "task-a",
  linkedMilestoneId: null,
  requiredDate: "2026-08-10",
  dispositionNote: null,
  sourceEvidence: "Defect list 42",
  createdAt: "2026-07-29T00:00:00Z",
  updatedAt: "2026-07-29T00:00:00Z",
};
