-- ── Relay-level moderator role ────────────────────────────────────────────────
-- Extends the `relay_members.role` CHECK to include 'moderator', enabling
-- community moderators who hold a scoped subset of admin capabilities
-- (ViewQueue, ResolveReport, DeleteMessage, Kick, Timeout, Untimeout) without
-- full relay-admin rights.
--
-- Additive migration: previously applied files must not change checksum.
--
-- PostgreSQL does not support ALTER TABLE ... ALTER CONSTRAINT, so we drop the
-- existing check constraint by name and add a new one. The constraint was
-- generated by the initial schema CREATE TABLE statement, so its name follows
-- the pg convention: relay_members_role_check.
--
-- Lock note: DROP/ADD CONSTRAINT takes an ACCESS EXCLUSIVE lock on
-- relay_members for the duration. The table is not written to by live traffic
-- during migrations (embedded startup serializes schema-first before serving),
-- so this is safe in one-image deployments. Environments that separate
-- migration from runtime should schedule this during low-traffic windows.

ALTER TABLE relay_members
    DROP CONSTRAINT IF EXISTS relay_members_role_check,
    ADD CONSTRAINT relay_members_role_check
        CHECK (role IN ('owner', 'admin', 'member', 'moderator'));
