use std::collections::BTreeSet;
use std::fmt;
use std::time::Duration;

use buzz_agent_pkg::lmstudio::{
    LmStudioChatRequest, LmStudioChatResponse, LmStudioOutput, LmStudioReasoning,
    MAX_CONTEXT_TOKENS, MAX_OUTPUT_TOKENS,
};
use buzz_agent_pkg::types::{AgentError, ExecutedToolProvider};
use buzz_agent_pkg::LmStudioNativeClient;
use chrono::{SecondsFormat, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use tokio_util::sync::CancellationToken;

use super::personas::definition_for;
use super::provenance::{build_evidence_prompt, ValidatedSource};
use super::types::{
    AdviserContribution, AdviserId, CitedFinding, Classification, MAX_AGGREGATE_DISSENT_ITEMS,
    MAX_ARRAY_ITEMS, MAX_SOURCE_LEDGER_ITEMS, MAX_TEXT_BYTES, SPECIALIST_ADVISERS,
    SPECIALIST_COUNT,
};
use crate::command_services::policy::{
    adviser_runtime_catalog, build_adviser_runtime_catalog, AdmissionError, AdviserRuntimeCatalog,
};

const MAX_REQUEST_IDENTITY_BYTES: usize = 1_024;
const MAX_MODEL_ID_BYTES: usize = 512;
const MAX_CHIEF_INPUT_BYTES: usize = 256 * 1024;

/// One specialist invocation assembled only from a closed adviser ID and
/// already-validated run sources.
#[derive(Clone)]
pub struct SpecialistAdviserRequest {
    request_identity: String,
    adviser: AdviserId,
    sources: Vec<ValidatedSource>,
}

impl fmt::Debug for SpecialistAdviserRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SpecialistAdviserRequest")
            .field("request_identity", &"[REDACTED]")
            .field("adviser", &self.adviser)
            .field("source_count", &self.sources.len())
            .finish()
    }
}

impl SpecialistAdviserRequest {
    /// Creates a specialist request without accepting prompts, model routes, or tools.
    pub fn new(
        request_identity: impl Into<String>,
        adviser: AdviserId,
        sources: Vec<ValidatedSource>,
    ) -> Self {
        Self {
            request_identity: request_identity.into(),
            adviser,
            sources,
        }
    }
}

/// A tool-free consolidation request containing only validated specialist
/// contributions and the frozen run ledger.
#[derive(Clone)]
pub struct ChiefOfStaffRequest {
    request_identity: String,
    contributions: Vec<AdviserContribution>,
    source_ledger: Vec<ValidatedSource>,
}

impl fmt::Debug for ChiefOfStaffRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ChiefOfStaffRequest")
            .field("request_identity", &"[REDACTED]")
            .field("contribution_count", &self.contributions.len())
            .field("source_count", &self.source_ledger.len())
            .finish()
    }
}

impl ChiefOfStaffRequest {
    /// Creates a consolidation request with no transport or integration inputs.
    pub fn new(
        request_identity: impl Into<String>,
        contributions: Vec<AdviserContribution>,
        source_ledger: Vec<ValidatedSource>,
    ) -> Self {
        Self {
            request_identity: request_identity.into(),
            contributions,
            source_ledger,
        }
    }
}

/// Token counts retained from one validated native response.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AdviserTokenCounts {
    /// Tokens consumed by the native request.
    pub input: u64,
    /// Total tokens generated by the native response.
    pub output: u64,
    /// Generated tokens attributed to hidden reasoning.
    pub reasoning: u64,
}

/// A bounded identity for an already-executed native MCP call. Tool arguments,
/// outputs, and provider response IDs are deliberately absent.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutedToolEvidenceIdentity {
    /// SHA-256 identifier derived from the request-scoped native call identity.
    pub call_id_hash: String,
    /// Catalog-admitted ephemeral MCP server label.
    pub server_label: String,
    /// Exact catalog-admitted tool name.
    pub tool_name: String,
}

/// Validated output plus persistence-safe execution metadata.
#[derive(Clone)]
pub struct AdviserExecutionResult<T> {
    /// Trusted structured output validated against the run ledger.
    pub contribution: T,
    /// Bounded local model instance reported by LM Studio.
    pub model_instance_id: String,
    /// SHA-256 digest of the provider response ID.
    pub response_id_hash: String,
    /// Provider-reported token counts.
    pub token_counts: AdviserTokenCounts,
    /// Identities of validated structured MCP outputs, without their content.
    pub executed_tool_evidence: Vec<ExecutedToolEvidenceIdentity>,
    /// Trusted local start timestamp.
    pub started_at: String,
    /// Trusted local completion timestamp.
    pub finished_at: String,
    /// Bounded metadata-only diagnostics; never prompts, reasoning, or evidence.
    pub diagnostics: Vec<String>,
}

impl<T> fmt::Debug for AdviserExecutionResult<T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AdviserExecutionResult")
            .field("contribution", &"[REDACTED]")
            .field("model_instance_id", &self.model_instance_id)
            .field("response_id_hash", &self.response_id_hash)
            .field("token_counts", &self.token_counts)
            .field("executed_tool_evidence", &self.executed_tool_evidence)
            .field("started_at", &self.started_at)
            .field("finished_at", &self.finished_at)
            .field("diagnostics", &self.diagnostics)
            .finish()
    }
}

/// Exact tool-free Chief of Staff consolidation.
#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ChiefOfStaffConsolidation {
    classification: Classification,
    adviser: AdviserId,
    findings: Vec<CitedFinding>,
    limitations: Vec<String>,
    dissent: Vec<String>,
}

impl fmt::Debug for ChiefOfStaffConsolidation {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ChiefOfStaffConsolidation")
            .field("adviser", &self.adviser)
            .field("finding_count", &self.findings.len())
            .field("limitation_count", &self.limitations.len())
            .field("dissent_count", &self.dissent.len())
            .finish()
    }
}

impl ChiefOfStaffConsolidation {
    /// Returns findings proven identical to validated specialist findings.
    pub fn findings(&self) -> &[CitedFinding] {
        &self.findings
    }

    /// Returns bounded consolidation limitations.
    pub fn limitations(&self) -> &[String] {
        &self.limitations
    }

    /// Returns the exact specialist dissent sequence.
    pub fn dissent(&self) -> &[String] {
        &self.dissent
    }
}

/// Stable failure classes suitable for persistence and UI status.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AdviserExecutionErrorCode {
    /// The run cancellation token fired.
    Cancelled,
    /// The trusted caller supplied an invalid bounded request.
    InvalidRequest,
    /// Catalog or native egress policy rejected the request.
    PolicyRejected,
    /// Local LM Studio authentication is unavailable.
    Authentication,
    /// The configured local model is unavailable.
    ModelUnavailable,
    /// The bounded native request timed out.
    Timeout,
    /// The native transport failed or returned a disallowed HTTP response.
    Transport,
    /// Structured tool evidence was not exactly catalog-admitted.
    EvidenceRejected,
    /// The terminal structured output failed its closed Rust contract.
    InvalidOutput,
}

/// A redacted adviser failure. Provider bodies, prompts, evidence, credentials,
/// and response IDs are never retained.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AdviserExecutionError {
    code: AdviserExecutionErrorCode,
    diagnostic: &'static str,
}

impl AdviserExecutionError {
    /// Returns the stable redacted failure class.
    pub const fn code(&self) -> AdviserExecutionErrorCode {
        self.code
    }

    /// Returns a bounded diagnostic containing no model-visible material.
    pub const fn diagnostic(&self) -> &'static str {
        self.diagnostic
    }

    pub(crate) const fn new(code: AdviserExecutionErrorCode, diagnostic: &'static str) -> Self {
        Self { code, diagnostic }
    }
}

pub(crate) const fn cloud_fallback_eligible(code: AdviserExecutionErrorCode) -> bool {
    matches!(
        code,
        AdviserExecutionErrorCode::Authentication
            | AdviserExecutionErrorCode::ModelUnavailable
            | AdviserExecutionErrorCode::Timeout
            | AdviserExecutionErrorCode::Transport
            | AdviserExecutionErrorCode::InvalidOutput
    )
}

impl fmt::Display for AdviserExecutionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.diagnostic)
    }
}

impl std::error::Error for AdviserExecutionError {}

/// Trusted local executor backed by the existing non-retrying LM Studio native client.
pub struct AdviserExecutor {
    model: String,
    specialist_client: LmStudioNativeClient,
    specialist_integrations: Vec<buzz_agent_pkg::lmstudio::EphemeralMcpIntegration>,
    chief_of_staff_client: LmStudioNativeClient,
}

impl fmt::Debug for AdviserExecutor {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AdviserExecutor")
            .field("model", &self.model)
            .field(
                "specialist_integration_count",
                &self.specialist_integrations.len(),
            )
            .finish_non_exhaustive()
    }
}

impl AdviserExecutor {
    /// Loads endpoint, integrations, tool allowlists, and credentials from the
    /// trusted Rust catalog and Keychain boundary.
    pub fn from_catalog(
        model: impl Into<String>,
        timeout: Duration,
    ) -> Result<Self, AdviserExecutionError> {
        let catalog = adviser_runtime_catalog().map_err(map_catalog_error)?;
        Self::new(model, catalog, timeout)
    }

    /// Builds the local adviser runtime with no model-callable source tools.
    /// Trusted-LAN evidence is collected and bounded by native Rust first.
    pub(crate) fn from_local_evidence_only(
        model: impl Into<String>,
        timeout: Duration,
    ) -> Result<Self, AdviserExecutionError> {
        let facts = crate::managed_agents::trusted_lmstudio_runtime_facts().map_err(|_| {
            AdviserExecutionError::new(
                AdviserExecutionErrorCode::Authentication,
                "LM Studio runtime unavailable",
            )
        })?;
        let catalog =
            build_adviser_runtime_catalog(&[], &facts.endpoint, facts.api_token.as_deref())
                .map_err(map_catalog_error)?;
        Self::new(model, catalog, timeout)
    }

    pub(crate) fn new(
        model: impl Into<String>,
        catalog: AdviserRuntimeCatalog,
        timeout: Duration,
    ) -> Result<Self, AdviserExecutionError> {
        let model = model.into();
        if !valid_identifier(&model, MAX_MODEL_ID_BYTES) {
            return Err(AdviserExecutionError::new(
                AdviserExecutionErrorCode::InvalidRequest,
                "adviser request rejected",
            ));
        }
        let specialist_runtime = catalog.specialist_runtime();
        let specialist_integrations = specialist_runtime.wire_integrations();
        let chief_of_staff_runtime = catalog.chief_of_staff_runtime();
        if !chief_of_staff_runtime.wire_integrations().is_empty() {
            return Err(AdviserExecutionError::new(
                AdviserExecutionErrorCode::PolicyRejected,
                "adviser runtime catalog rejected",
            ));
        }
        let specialist_client =
            LmStudioNativeClient::new(specialist_runtime, timeout).map_err(map_native_error)?;
        let chief_of_staff_client =
            LmStudioNativeClient::new(chief_of_staff_runtime, timeout).map_err(map_native_error)?;
        Ok(Self {
            model,
            specialist_client,
            specialist_integrations,
            chief_of_staff_client,
        })
    }

    /// Executes one fixed specialist with catalog-admitted Memory/RAG integrations.
    pub async fn run_specialist(
        &self,
        request: SpecialistAdviserRequest,
        cancellation: CancellationToken,
    ) -> Result<AdviserExecutionResult<AdviserContribution>, AdviserExecutionError> {
        if request.adviser == AdviserId::ChiefOfStaff
            || !valid_identifier(&request.request_identity, MAX_REQUEST_IDENTITY_BYTES)
        {
            return Err(AdviserExecutionError::new(
                AdviserExecutionErrorCode::InvalidRequest,
                "adviser request rejected",
            ));
        }
        validate_source_collection(&request.sources)?;
        let persona = definition_for(request.adviser);
        let evidence = build_evidence_prompt(persona, &request.sources);
        let evidence_value: Value =
            serde_json::from_str(&evidence.evidence_json).map_err(|_| {
                AdviserExecutionError::new(
                    AdviserExecutionErrorCode::PolicyRejected,
                    "adviser evidence envelope rejected",
                )
            })?;
        let input = serde_json::to_string(&json!({
            "classification": "OFFICIAL",
            "evidence": evidence_value,
            "evidenceLimitations": evidence.limitations,
        }))
        .map_err(|_| {
            AdviserExecutionError::new(
                AdviserExecutionErrorCode::PolicyRejected,
                "adviser evidence envelope rejected",
            )
        })?;
        let ledger_ids = evidence
            .envelopes
            .iter()
            .map(|source| source.ledger_id.clone())
            .collect::<BTreeSet<_>>();
        let native_request = LmStudioChatRequest::new(
            &self.model,
            input,
            evidence.system_prompt,
            self.specialist_integrations.clone(),
            LmStudioReasoning::Off,
            MAX_OUTPUT_TOKENS,
            MAX_CONTEXT_TOKENS,
        )
        .map_err(map_native_error)?;
        let execution = execute_native(
            &self.specialist_client,
            &native_request,
            &request.request_identity,
            cancellation,
        )
        .await?;
        let terminal = terminal_message(&execution.response)?;
        let value = serde_json::from_str(terminal).map_err(|_| {
            AdviserExecutionError::new(
                AdviserExecutionErrorCode::InvalidOutput,
                "adviser output rejected",
            )
        })?;
        let contribution =
            AdviserContribution::parse_for_adviser(value, request.adviser, &ledger_ids).map_err(
                |_| {
                    AdviserExecutionError::new(
                        AdviserExecutionErrorCode::InvalidOutput,
                        "adviser output rejected",
                    )
                },
            )?;
        Ok(finish_execution(contribution, execution))
    }

    /// Executes the Chief of Staff with a separately validated empty-integration runtime.
    pub async fn run_chief_of_staff(
        &self,
        request: ChiefOfStaffRequest,
        cancellation: CancellationToken,
    ) -> Result<AdviserExecutionResult<ChiefOfStaffConsolidation>, AdviserExecutionError> {
        if !valid_identifier(&request.request_identity, MAX_REQUEST_IDENTITY_BYTES) {
            return Err(AdviserExecutionError::new(
                AdviserExecutionErrorCode::InvalidRequest,
                "adviser request rejected",
            ));
        }
        let (input, ledger_ids, allowed_findings, expected_dissent) = build_chief_input(&request)?;
        let persona = definition_for(AdviserId::ChiefOfStaff);
        let native_request = LmStudioChatRequest::new(
            &self.model,
            input,
            persona.system_prompt(),
            Vec::new(),
            LmStudioReasoning::Off,
            MAX_OUTPUT_TOKENS,
            MAX_CONTEXT_TOKENS,
        )
        .map_err(map_native_error)?;
        let execution = execute_native(
            &self.chief_of_staff_client,
            &native_request,
            &request.request_identity,
            cancellation,
        )
        .await?;
        if execution
            .response
            .output
            .iter()
            .any(|output| matches!(output, LmStudioOutput::ToolCall(_)))
        {
            return Err(AdviserExecutionError::new(
                AdviserExecutionErrorCode::EvidenceRejected,
                "executed tool evidence rejected",
            ));
        }
        let terminal = terminal_message(&execution.response)?;
        let consolidation =
            parse_chief_output(terminal, &ledger_ids, &allowed_findings, &expected_dissent)?;
        Ok(finish_execution(consolidation, execution))
    }
}

pub(crate) fn cloud_specialist_payload(
    request: &SpecialistAdviserRequest,
) -> Result<(&'static str, String), AdviserExecutionError> {
    if request.adviser == AdviserId::ChiefOfStaff
        || !valid_identifier(&request.request_identity, MAX_REQUEST_IDENTITY_BYTES)
    {
        return Err(invalid_request());
    }
    validate_source_collection(&request.sources)?;
    let persona = definition_for(request.adviser);
    let evidence = build_evidence_prompt(persona, &request.sources);
    let evidence_value: Value =
        serde_json::from_str(&evidence.evidence_json).map_err(|_| invalid_request())?;
    let input = serde_json::to_string(&json!({
        "classification": "OFFICIAL",
        "evidence": evidence_value,
        "evidenceLimitations": evidence.limitations,
    }))
    .map_err(|_| invalid_request())?;
    Ok((persona.system_prompt(), input))
}

pub(crate) fn parse_cloud_specialist_output(
    request: &SpecialistAdviserRequest,
    terminal: &str,
) -> Result<AdviserContribution, AdviserExecutionError> {
    let ledger_ids = request
        .sources
        .iter()
        .map(|source| source.ledger_id().to_string())
        .collect::<BTreeSet<_>>();
    let value = serde_json::from_str(terminal).map_err(|_| invalid_output())?;
    AdviserContribution::parse_for_adviser(value, request.adviser, &ledger_ids)
        .map_err(|_| invalid_output())
}

pub(crate) fn cloud_chief_payload(
    request: &ChiefOfStaffRequest,
) -> Result<(&'static str, String), AdviserExecutionError> {
    let (input, _, _, _) = build_chief_input(request)?;
    Ok((
        definition_for(AdviserId::ChiefOfStaff).system_prompt(),
        input,
    ))
}

pub(crate) fn parse_cloud_chief_output(
    request: &ChiefOfStaffRequest,
    terminal: &str,
) -> Result<ChiefOfStaffConsolidation, AdviserExecutionError> {
    let (_, ledger_ids, allowed_findings, expected_dissent) = build_chief_input(request)?;
    parse_chief_output(terminal, &ledger_ids, &allowed_findings, &expected_dissent)
}

struct NativeExecution {
    response: LmStudioChatResponse,
    started_at: String,
    finished_at: String,
    diagnostics: Vec<String>,
}

async fn execute_native(
    client: &LmStudioNativeClient,
    request: &LmStudioChatRequest,
    request_identity: &str,
    cancellation: CancellationToken,
) -> Result<NativeExecution, AdviserExecutionError> {
    if cancellation.is_cancelled() {
        return Err(AdviserExecutionError::new(
            AdviserExecutionErrorCode::Cancelled,
            "adviser execution cancelled",
        ));
    }
    let started_at = timestamp();
    let response = tokio::select! {
        biased;
        _ = cancellation.cancelled() => {
            return Err(AdviserExecutionError::new(
                AdviserExecutionErrorCode::Cancelled,
                "adviser execution cancelled",
            ));
        }
        response = client.chat(request, request_identity) => {
            response.map_err(map_native_error)?
        }
    };
    let finished_at = timestamp();
    let reasoning_items = response
        .output
        .iter()
        .filter(|output| matches!(output, LmStudioOutput::Reasoning { .. }))
        .count();
    let diagnostics = if reasoning_items > 0 {
        vec![format!("reasoning_items={reasoning_items}")]
    } else {
        Vec::new()
    };
    Ok(NativeExecution {
        response,
        started_at,
        finished_at,
        diagnostics,
    })
}

fn finish_execution<T>(contribution: T, execution: NativeExecution) -> AdviserExecutionResult<T> {
    let executed_tool_evidence = execution
        .response
        .output
        .iter()
        .filter_map(|output| {
            let LmStudioOutput::ToolCall(call) = output else {
                return None;
            };
            let ExecutedToolProvider::EphemeralMcp { server_label } = &call.provider else {
                return None;
            };
            Some(ExecutedToolEvidenceIdentity {
                call_id_hash: hash_identifier(&call.provider_id),
                server_label: server_label.clone(),
                tool_name: call.name.clone(),
            })
        })
        .collect();
    AdviserExecutionResult {
        contribution,
        model_instance_id: execution.response.model_instance_id,
        response_id_hash: hash_identifier(&execution.response.response_id),
        token_counts: AdviserTokenCounts {
            input: execution.response.stats.input_tokens,
            output: execution.response.stats.total_output_tokens,
            reasoning: execution.response.stats.reasoning_output_tokens,
        },
        executed_tool_evidence,
        started_at: execution.started_at,
        finished_at: execution.finished_at,
        diagnostics: execution.diagnostics,
    }
}

fn terminal_message(response: &LmStudioChatResponse) -> Result<&str, AdviserExecutionError> {
    match response.output.last() {
        Some(LmStudioOutput::Message { content }) => Ok(content),
        _ => Err(AdviserExecutionError::new(
            AdviserExecutionErrorCode::InvalidOutput,
            "adviser output rejected",
        )),
    }
}

type ChiefInputValidation = (
    String,
    BTreeSet<String>,
    BTreeSet<(String, Vec<String>)>,
    Vec<String>,
);

fn build_chief_input(
    request: &ChiefOfStaffRequest,
) -> Result<ChiefInputValidation, AdviserExecutionError> {
    validate_source_collection(&request.source_ledger)?;
    if request.contributions.len() != SPECIALIST_COUNT {
        return Err(invalid_request());
    }
    let expected_advisers = BTreeSet::from(SPECIALIST_ADVISERS);
    let mut advisers = BTreeSet::new();
    let mut allowed_findings = BTreeSet::new();
    let mut expected_dissent = Vec::new();
    for contribution in &request.contributions {
        if !expected_advisers.contains(&contribution.adviser())
            || !advisers.insert(contribution.adviser())
        {
            return Err(invalid_request());
        }
        for finding in contribution.findings() {
            allowed_findings.insert((finding.text().to_string(), finding.source_ids().to_vec()));
        }
        expected_dissent.extend(contribution.dissent().iter().cloned());
    }
    if advisers != expected_advisers || expected_dissent.len() > MAX_AGGREGATE_DISSENT_ITEMS {
        return Err(invalid_request());
    }
    let ledger_ids = request
        .source_ledger
        .iter()
        .map(|source| source.ledger_id().to_string())
        .collect::<BTreeSet<_>>();
    if ledger_ids.len() != request.source_ledger.len()
        || allowed_findings.iter().any(|(_, source_ids)| {
            source_ids
                .iter()
                .any(|source_id| !ledger_ids.contains(source_id))
        })
    {
        return Err(invalid_request());
    }
    let source_ledger = request
        .source_ledger
        .iter()
        .map(|source| {
            json!({
                "classification": "OFFICIAL",
                "ledgerId": source.ledger_id(),
                "sourceKind": source.source_kind(),
                "sourceId": source.source_id(),
                "collection": source.collection(),
                "documentId": source.document_id(),
                "chunkId": source.chunk_id(),
                "snapshotId": source.snapshot_id(),
                "observedAt": source.observed_at(),
                "retrievedAt": source.retrieved_at(),
                "quotedLocation": {
                    "location": source.location(),
                    "quote": source.quote(),
                },
                "untrustedEvidence": true,
            })
        })
        .collect::<Vec<_>>();
    let input = serde_json::to_string(&json!({
        "classification": "OFFICIAL",
        "validatedContributions": request.contributions,
        "sourceLedger": source_ledger,
    }))
    .map_err(|_| invalid_request())?;
    if input.len() > MAX_CHIEF_INPUT_BYTES {
        return Err(invalid_request());
    }
    Ok((input, ledger_ids, allowed_findings, expected_dissent))
}

fn validate_source_collection(sources: &[ValidatedSource]) -> Result<(), AdviserExecutionError> {
    if sources.len() > MAX_SOURCE_LEDGER_ITEMS {
        return Err(invalid_request());
    }
    let mut ledger_ids = BTreeSet::new();
    let mut source_ids = BTreeSet::new();
    let mut snapshot_ids = BTreeSet::new();
    for source in sources {
        if !ledger_ids.insert(source.ledger_id()) || !source_ids.insert(source.source_id()) {
            return Err(invalid_request());
        }
        snapshot_ids.insert(source.snapshot_id());
    }
    if snapshot_ids.len() > 1 {
        return Err(invalid_request());
    }
    Ok(())
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct RawChiefOutput {
    classification: Classification,
    adviser: AdviserId,
    findings: Vec<Value>,
    limitations: Vec<String>,
    dissent: Vec<String>,
}

fn parse_chief_output(
    terminal: &str,
    ledger_ids: &BTreeSet<String>,
    allowed_findings: &BTreeSet<(String, Vec<String>)>,
    expected_dissent: &[String],
) -> Result<ChiefOfStaffConsolidation, AdviserExecutionError> {
    let raw: RawChiefOutput = serde_json::from_str(terminal).map_err(|_| invalid_output())?;
    if raw.adviser != AdviserId::ChiefOfStaff
        || raw.findings.len() > MAX_ARRAY_ITEMS
        || !valid_text_array(&raw.limitations)
        || !valid_text_array_with_limit(&raw.dissent, MAX_AGGREGATE_DISSENT_ITEMS)
        || raw.dissent != expected_dissent
    {
        return Err(invalid_output());
    }
    let mut seen = BTreeSet::new();
    let mut findings = Vec::with_capacity(raw.findings.len());
    for value in raw.findings {
        let finding =
            CitedFinding::parse_for_ledger(value, ledger_ids).map_err(|_| invalid_output())?;
        let identity = (finding.text().to_string(), finding.source_ids().to_vec());
        if !allowed_findings.contains(&identity) || !seen.insert(identity) {
            return Err(invalid_output());
        }
        findings.push(finding);
    }
    Ok(ChiefOfStaffConsolidation {
        classification: raw.classification,
        adviser: raw.adviser,
        findings,
        limitations: raw.limitations,
        dissent: raw.dissent,
    })
}

fn valid_identifier(value: &str, maximum_bytes: usize) -> bool {
    !value.is_empty()
        && value.trim() == value
        && value.len() <= maximum_bytes
        && !value.chars().any(char::is_control)
}

fn valid_text_array(values: &[String]) -> bool {
    valid_text_array_with_limit(values, MAX_ARRAY_ITEMS)
}

fn valid_text_array_with_limit(values: &[String], maximum_items: usize) -> bool {
    values.len() <= maximum_items
        && values
            .iter()
            .all(|value| valid_identifier(value, MAX_TEXT_BYTES))
}

fn hash_identifier(value: &str) -> String {
    format!("sha256:{}", hex::encode(Sha256::digest(value.as_bytes())))
}

fn timestamp() -> String {
    Utc::now().to_rfc3339_opts(SecondsFormat::Millis, true)
}

fn invalid_request() -> AdviserExecutionError {
    AdviserExecutionError::new(
        AdviserExecutionErrorCode::InvalidRequest,
        "adviser request rejected",
    )
}

fn invalid_output() -> AdviserExecutionError {
    AdviserExecutionError::new(
        AdviserExecutionErrorCode::InvalidOutput,
        "adviser output rejected",
    )
}

fn map_native_error(error: AgentError) -> AdviserExecutionError {
    match error {
        AgentError::Cancelled => AdviserExecutionError::new(
            AdviserExecutionErrorCode::Cancelled,
            "adviser execution cancelled",
        ),
        AgentError::InvalidParams(_) => AdviserExecutionError::new(
            AdviserExecutionErrorCode::PolicyRejected,
            "adviser native policy rejected",
        ),
        AgentError::LlmAuth(_) => AdviserExecutionError::new(
            AdviserExecutionErrorCode::Authentication,
            "local model authentication unavailable",
        ),
        AgentError::LlmModelNotFound(_) => AdviserExecutionError::new(
            AdviserExecutionErrorCode::ModelUnavailable,
            "local model unavailable",
        ),
        AgentError::Mcp(_) => AdviserExecutionError::new(
            AdviserExecutionErrorCode::EvidenceRejected,
            "executed tool evidence rejected",
        ),
        AgentError::Llm(message) if message == "LM Studio native request timed out" => {
            AdviserExecutionError::new(
                AdviserExecutionErrorCode::Timeout,
                "local model request timed out",
            )
        }
        AgentError::Llm(message)
            if message.starts_with("egress denied:")
                || message.starts_with("command evidence rejected:") =>
        {
            AdviserExecutionError::new(
                AdviserExecutionErrorCode::EvidenceRejected,
                "executed tool evidence rejected",
            )
        }
        AgentError::Llm(message)
            if message.starts_with("malformed native")
                || message.starts_with("native invalid tool call")
                || message == "native response is missing a terminal message" =>
        {
            AdviserExecutionError::new(
                AdviserExecutionErrorCode::InvalidOutput,
                "adviser output rejected",
            )
        }
        AgentError::Llm(_) => AdviserExecutionError::new(
            AdviserExecutionErrorCode::Transport,
            "local model transport failed",
        ),
    }
}

fn map_catalog_error(error: AdmissionError) -> AdviserExecutionError {
    if error.is_authentication_failure() {
        AdviserExecutionError::new(
            AdviserExecutionErrorCode::Authentication,
            "local model authentication unavailable",
        )
    } else {
        AdviserExecutionError::new(
            AdviserExecutionErrorCode::PolicyRejected,
            "adviser runtime catalog rejected",
        )
    }
}
