[[rules]]
name = "mechanon-private-office"
channels = ["7d022bea-5e81-4d18-bd2e-176e9eda1971"]
kinds = [9, 40002]
require_exact_channel_tag = true
require_mention = false
filter = 'author == "73ac8798fd9cedcc5d24645d7ed49332d94a28f2c937f4c1b638f92bf6e8e91f"'

[[rules]]
name = "mechanon-invited-huddle"
channels = []
admit_invited_ephemeral = true
kinds = [9, 40002]
require_exact_channel_tag = true
require_mention = true
filter = 'author == "73ac8798fd9cedcc5d24645d7ed49332d94a28f2c937f4c1b638f92bf6e8e91f"'
