//! Member-visible, privacy-sanitized managed-agent activity frames.
//!
//! This module is deliberately independent from [`crate::observer`]. Observer
//! frames are owner-only and may contain full ACP payloads; activity frames are
//! a closed, channel-scoped projection suitable for current channel members.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Deserializer, Serialize};
use thiserror::Error;
use uuid::Uuid;

/// Current member-visible activity frame schema version.
pub const AGENT_ACTIVITY_FRAME_VERSION: u8 = 1;
/// Maximum activities carried by one ephemeral event.
pub const AGENT_ACTIVITY_MAX_ITEMS: usize = 32;
/// Maximum serialized JSON bytes for one activity frame.
pub const AGENT_ACTIVITY_MAX_FRAME_BYTES: usize = 4_096;
/// Maximum reported duration (seven days).
pub const AGENT_ACTIVITY_MAX_DURATION_MS: u64 = 7 * 24 * 60 * 60 * 1_000;
/// Maximum accepted token count in a single usage field.
pub const AGENT_ACTIVITY_MAX_TOKEN_COUNT: u64 = 1_000_000_000_000;
/// Exact cleartext tag name containing the authoring agent pubkey.
pub const AGENT_ACTIVITY_AGENT_TAG: &str = "agent";

/// Errors returned while parsing or validating shared activity frames.
#[derive(Debug, Error)]
pub enum AgentActivityError {
    /// The serialized frame exceeds the protocol byte cap.
    #[error("agent activity frame too large: maximum {max} bytes, got {got}")]
    FrameTooLarge {
        /// Maximum accepted bytes.
        max: usize,
        /// Actual bytes.
        got: usize,
    },
    /// JSON serialization or deserialization failed.
    #[error("invalid agent activity JSON: {0}")]
    Json(#[from] serde_json::Error),
    /// A semantic schema invariant failed.
    #[error("invalid agent activity frame: {0}")]
    Invalid(String),
}

/// One ephemeral frame containing a bounded set of sanitized activities.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AgentActivityFrame {
    /// Schema version. Must equal [`AGENT_ACTIVITY_FRAME_VERSION`].
    pub version: u8,
    /// Ordered activity updates.
    pub activities: Vec<AgentActivity>,
}

impl AgentActivityFrame {
    /// Parse and validate a frame from bounded JSON content.
    pub fn parse(content: &str) -> Result<Self, AgentActivityError> {
        check_frame_size(content.len())?;
        let frame: Self = serde_json::from_str(content)?;
        frame.validate()?;
        Ok(frame)
    }

    /// Validate and serialize a frame to compact JSON.
    pub fn to_json(&self) -> Result<String, AgentActivityError> {
        self.validate()?;
        let content = serde_json::to_string(self)?;
        check_frame_size(content.len())?;
        Ok(content)
    }

    /// Validate all closed-schema semantic invariants.
    pub fn validate(&self) -> Result<(), AgentActivityError> {
        if self.version != AGENT_ACTIVITY_FRAME_VERSION {
            return Err(AgentActivityError::Invalid(format!(
                "unsupported version {}",
                self.version
            )));
        }
        if self.activities.is_empty() || self.activities.len() > AGENT_ACTIVITY_MAX_ITEMS {
            return Err(AgentActivityError::Invalid(format!(
                "activities must contain 1..={AGENT_ACTIVITY_MAX_ITEMS} items"
            )));
        }
        for activity in &self.activities {
            activity.validate()?;
        }
        Ok(())
    }
}

fn check_frame_size(got: usize) -> Result<(), AgentActivityError> {
    if got > AGENT_ACTIVITY_MAX_FRAME_BYTES {
        return Err(AgentActivityError::FrameTooLarge {
            max: AGENT_ACTIVITY_MAX_FRAME_BYTES,
            got,
        });
    }
    Ok(())
}

/// A single sanitized lifecycle, tool, or usage update.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AgentActivity {
    /// Random opaque identifier generated by the producer.
    pub activity_id: Uuid,
    /// UTC occurrence time.
    pub occurred_at: DateTime<Utc>,
    /// Closed activity class.
    pub activity_class: AgentActivityClass,
    /// Closed lifecycle status.
    pub status: AgentActivityStatus,
    /// Safe tool category. Present only for tool activity.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tool_kind: Option<AgentActivityToolKind>,
    /// Bounded elapsed duration. Present only for terminal turn/tool updates.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub duration_ms: Option<u64>,
    /// Per-turn token counts. Present only for completed usage updates.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub usage: Option<AgentActivityUsage>,
}

fn deserialize_non_null_option<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    T::deserialize(deserializer).map(Some)
}

impl AgentActivity {
    fn validate(&self) -> Result<(), AgentActivityError> {
        if self
            .duration_ms
            .is_some_and(|duration| duration > AGENT_ACTIVITY_MAX_DURATION_MS)
        {
            return Err(AgentActivityError::Invalid(format!(
                "durationMs exceeds {AGENT_ACTIVITY_MAX_DURATION_MS}"
            )));
        }

        if self.duration_ms.is_some()
            && !matches!(
                self.status,
                AgentActivityStatus::Completed
                    | AgentActivityStatus::Failed
                    | AgentActivityStatus::Cancelled
            )
        {
            return Err(AgentActivityError::Invalid(
                "durationMs is allowed only on terminal status updates".into(),
            ));
        }

        match self.activity_class {
            AgentActivityClass::Turn => {
                if self.tool_kind.is_some() || self.usage.is_some() {
                    return Err(AgentActivityError::Invalid(
                        "turn activity forbids toolKind and usage".into(),
                    ));
                }
                if self.status == AgentActivityStatus::Pending {
                    return Err(AgentActivityError::Invalid(
                        "turn activity does not support pending status".into(),
                    ));
                }
            }
            AgentActivityClass::Tool => {
                if self.tool_kind.is_none() {
                    return Err(AgentActivityError::Invalid(
                        "tool activity requires toolKind".into(),
                    ));
                }
                if self.usage.is_some() {
                    return Err(AgentActivityError::Invalid(
                        "tool activity forbids usage".into(),
                    ));
                }
                if self.status == AgentActivityStatus::Started {
                    return Err(AgentActivityError::Invalid(
                        "tool activity uses pending or running rather than started".into(),
                    ));
                }
            }
            AgentActivityClass::Usage => {
                if self.status != AgentActivityStatus::Completed {
                    return Err(AgentActivityError::Invalid(
                        "usage activity requires completed status".into(),
                    ));
                }
                if self.tool_kind.is_some() || self.duration_ms.is_some() {
                    return Err(AgentActivityError::Invalid(
                        "usage activity forbids toolKind and durationMs".into(),
                    ));
                }
                let usage = self.usage.as_ref().ok_or_else(|| {
                    AgentActivityError::Invalid("usage activity requires usage".into())
                })?;
                usage.validate()?;
            }
        }
        Ok(())
    }
}

/// Sanitized activity class.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentActivityClass {
    /// Agent turn lifecycle.
    Turn,
    /// Tool lifecycle with only a safe category.
    Tool,
    /// Reliable per-turn token usage.
    Usage,
}

/// Sanitized lifecycle status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentActivityStatus {
    /// Turn began.
    Started,
    /// Tool was announced but has not started.
    Pending,
    /// Turn or tool is active.
    Running,
    /// Turn, tool, or usage completed successfully.
    Completed,
    /// Turn or tool failed, without error details.
    Failed,
    /// Turn or tool was cancelled.
    Cancelled,
}

/// Closed, non-user-controlled tool category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentActivityToolKind {
    /// Read-only data access.
    Read,
    /// File or record modification.
    Edit,
    /// Deletion.
    Delete,
    /// Move or rename.
    Move,
    /// Search or lookup.
    Search,
    /// Command or program execution.
    Execute,
    /// Internal planning category; rendered neutrally, never as chain-of-thought.
    Think,
    /// Remote fetch.
    Fetch,
    /// Mode switch.
    SwitchMode,
    /// Any unrecognized tool category.
    Other,
}

/// Reliable per-turn token counts, without provider, model, price, or cumulative totals.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AgentActivityUsage {
    /// Input tokens for this turn.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_tokens: Option<u64>,
    /// Output tokens for this turn.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub output_tokens: Option<u64>,
    /// Total tokens for this turn.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_tokens: Option<u64>,
    /// Cache-read tokens for this turn.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_read_tokens: Option<u64>,
    /// Cache-write tokens for this turn.
    #[serde(
        default,
        deserialize_with = "deserialize_non_null_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_write_tokens: Option<u64>,
}

impl AgentActivityUsage {
    fn validate(&self) -> Result<(), AgentActivityError> {
        let counts = [
            self.input_tokens,
            self.output_tokens,
            self.total_tokens,
            self.cache_read_tokens,
            self.cache_write_tokens,
        ];
        if counts.iter().all(Option::is_none) {
            return Err(AgentActivityError::Invalid(
                "usage requires at least one token count".into(),
            ));
        }
        if counts
            .iter()
            .flatten()
            .any(|count| *count > AGENT_ACTIVITY_MAX_TOKEN_COUNT)
        {
            return Err(AgentActivityError::Invalid(format!(
                "usage count exceeds {AGENT_ACTIVITY_MAX_TOKEN_COUNT}"
            )));
        }
        Ok(())
    }
}
