import type { GraphNodeDto, GraphLinkDto } from "./types";

export function getSampleBrainGraph(): {
  nodes: GraphNodeDto[];
  links: GraphLinkDto[];
} {
  const nodes: GraphNodeDto[] = [
    {
      id: "node-proj-orbit",
      name: "Orbit Monorepo",
      entity_type: "project",
      description: "Local-first AI memory & context engine for developer teams.",
      metadata: { repo: "block/buzz", language: "Rust / TypeScript" },
      created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    },
    {
      id: "node-proj-desktop",
      name: "Desktop Client",
      entity_type: "project",
      description: "Tauri 2 + React 19 desktop app for Orbit intelligence.",
      metadata: { framework: "Tauri 2", ui: "React 19" },
      created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    },
    {
      id: "node-agent-antigravity",
      name: "Antigravity",
      entity_type: "agent",
      description: "Advanced agentic pair programmer by DeepMind.",
      metadata: { harness: "AGY CLI", connected: true },
      created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    },
    {
      id: "node-agent-claude",
      name: "Claude Code",
      entity_type: "agent",
      description: "Anthropic terminal agent connected via MCP stdio.",
      metadata: { harness: "Claude CLI", connected: true },
      created_at: new Date(Date.now() - 86400000 * 9).toISOString(),
    },
    {
      id: "node-agent-cursor",
      name: "Cursor",
      entity_type: "agent",
      description: "AI code editor connected via .cursor/mcp.json.",
      metadata: { harness: "Cursor IDE", connected: true },
      created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    },
    {
      id: "node-chat-superrag",
      name: "Chat: SuperRAG Hybrid Search",
      entity_type: "chat",
      description: "Discussion on dense LanceDB + lexical FTS5 rank fusion.",
      metadata: { channel: "engineering", author: "Antigravity" },
      created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      id: "node-chat-ingest",
      name: "Chat: Ingestion Pipeline",
      entity_type: "chat",
      description: "Tree-sitter multi-language AST chunking specifications.",
      metadata: { channel: "architecture", author: "Claude Code" },
      created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    },
    {
      id: "node-file-sqlite",
      name: "sqlite.rs",
      entity_type: "file",
      description: "SQLite authoritative storage metadata implementation in buzz-db.",
      metadata: { path: "crates/buzz-db/src/memory/sqlite.rs", lines: 480 },
      created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    },
    {
      id: "node-file-bge",
      name: "bge-small-en-v1.5.onnx",
      entity_type: "file",
      description: "Quantized ONNX model bundle running offline CPU embeddings (<5ms).",
      metadata: { dimensions: 384, provider: "ort" },
      created_at: new Date(Date.now() - 86400000 * 11).toISOString(),
    },
    {
      id: "node-file-braingraph",
      name: "BrainGraph.tsx",
      entity_type: "file",
      description: "Obsidian-style D3 force canvas renderer for desktop.",
      metadata: { path: "desktop/src/features/memory/BrainGraph.tsx" },
      created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: "node-dec-localfirst",
      name: "ADR-001: Zero-Docker Local-First Store",
      entity_type: "decision",
      description: "Architectural Decision: Embedded SQLite + LanceDB with zero external daemon requirement.",
      metadata: { status: "accepted", superseded_by: null },
      created_at: new Date(Date.now() - 86400000 * 13).toISOString(),
    },
    {
      id: "node-dec-reranker",
      name: "ADR-002: BGE Cross-Encoder Reranker",
      entity_type: "decision",
      description: "Use BGE-reranker-small over raw cosine similarity to prune top 50 candidates to top 15 precision results.",
      metadata: { status: "accepted", superseded_by: null },
      created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    },
    {
      id: "node-dec-legacy-fts",
      name: "ADR-Legacy: Standalone ElasticSearch",
      entity_type: "decision",
      description: "Legacy proposal to run standalone search cluster for indexing.",
      metadata: { status: "superseded", superseded_by: "ADR-001" },
      created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    },
    {
      id: "node-concept-lancedb",
      name: "LanceDB Vector Storage",
      entity_type: "concept",
      description: "Serverless columnar vector database format for high-throughput local ANN.",
      metadata: { index: "IVF-PQ", metric: "cosine" },
      created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    },
    {
      id: "node-concept-treesitter",
      name: "Tree-Sitter AST Chunker",
      entity_type: "concept",
      description: "Syntax-aware AST parsing preserving semantic function boundaries.",
      metadata: { supported_languages: ["Rust", "TypeScript", "Python", "Go", "Markdown"] },
      created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    },
    {
      id: "node-concept-bitemporal",
      name: "Bi-Temporal Graphiti Memory",
      entity_type: "concept",
      description: "Double timestamping (valid_at, invalid_at) tracking evolution and contradiction invalidation.",
      metadata: { model: "Graphiti" },
      created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    },
  ];

  const links: GraphLinkDto[] = [
    {
      id: "link-1",
      source: "node-proj-orbit",
      target: "node-proj-desktop",
      relation_type: "depends_on",
      confidence: 1.0,
      valid_at: new Date(Date.now() - 86400000 * 12).toISOString(),
      is_active: true,
    },
    {
      id: "link-2",
      source: "node-agent-antigravity",
      target: "node-chat-superrag",
      relation_type: "authored_by",
      confidence: 0.98,
      valid_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      is_active: true,
    },
    {
      id: "link-3",
      source: "node-agent-claude",
      target: "node-chat-ingest",
      relation_type: "authored_by",
      confidence: 0.95,
      valid_at: new Date(Date.now() - 86400000 * 6).toISOString(),
      is_active: true,
    },
    {
      id: "link-4",
      source: "node-chat-superrag",
      target: "node-dec-reranker",
      relation_type: "decided_in",
      confidence: 0.99,
      valid_at: new Date(Date.now() - 86400000 * 4).toISOString(),
      is_active: true,
    },
    {
      id: "link-5",
      source: "node-chat-superrag",
      target: "node-concept-lancedb",
      relation_type: "mentions",
      confidence: 0.92,
      valid_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      is_active: true,
    },
    {
      id: "link-6",
      source: "node-chat-ingest",
      target: "node-concept-treesitter",
      relation_type: "mentions",
      confidence: 0.96,
      valid_at: new Date(Date.now() - 86400000 * 6).toISOString(),
      is_active: true,
    },
    {
      id: "link-7",
      source: "node-file-sqlite",
      target: "node-dec-localfirst",
      relation_type: "depends_on",
      confidence: 0.97,
      valid_at: new Date(Date.now() - 86400000 * 7).toISOString(),
      is_active: true,
    },
    {
      id: "link-8",
      source: "node-file-bge",
      target: "node-dec-reranker",
      relation_type: "depends_on",
      confidence: 0.94,
      valid_at: new Date(Date.now() - 86400000 * 4).toISOString(),
      is_active: true,
    },
    {
      id: "link-9",
      source: "node-dec-localfirst",
      target: "node-dec-legacy-fts",
      relation_type: "supersedes",
      confidence: 1.0,
      valid_at: new Date(Date.now() - 86400000 * 13).toISOString(),
      invalid_at: new Date(Date.now() - 86400000 * 13).toISOString(),
      is_active: false,
    },
    {
      id: "link-10",
      source: "node-proj-desktop",
      target: "node-file-braingraph",
      relation_type: "depends_on",
      confidence: 0.99,
      valid_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      is_active: true,
    },
    {
      id: "link-11",
      source: "node-concept-bitemporal",
      target: "node-file-sqlite",
      relation_type: "mentions",
      confidence: 0.9,
      valid_at: new Date(Date.now() - 86400000 * 8).toISOString(),
      is_active: true,
    },
    {
      id: "link-12",
      source: "node-agent-cursor",
      target: "node-proj-orbit",
      relation_type: "worked_on",
      confidence: 0.91,
      valid_at: new Date(Date.now() - 86400000 * 8).toISOString(),
      is_active: true,
    },
  ];

  return { nodes, links };
}
