import type { ComponentType } from "react";
import * as forms from "./forms";
import formsSource from "./forms.tsx?raw";
import * as overlays from "./overlays";
import overlaysSource from "./overlays.tsx?raw";
import * as navigation from "./navigation";
import navigationSource from "./navigation.tsx?raw";
import * as display from "./display";
import displaySource from "./display.tsx?raw";

/** A live example and its source, grouped by the job it does. */
export interface CatalogEntry {
  id: string;
  name: string;
  description: string;
  category: string;
  Preview: ComponentType;
  source: string;
}
export const CATALOG: readonly CatalogEntry[] = [
  {
    id: "buttons",
    name: "Buttons",
    description: "Six emphasis variants, three sizes, and named icon actions.",
    category: "Inputs",
    Preview: forms.ButtonsDemo,
    source: formsSource,
  },
  {
    id: "input",
    name: "Input",
    description: "A single-line field with an associated label.",
    category: "Inputs",
    Preview: forms.InputDemo,
    source: formsSource,
  },
  {
    id: "textarea",
    name: "Textarea",
    description: "A growing space for longer thoughts.",
    category: "Inputs",
    Preview: forms.TextareaDemo,
    source: formsSource,
  },
  {
    id: "input-group",
    name: "Input group",
    description: "Accessories around one clearly labeled input.",
    category: "Inputs",
    Preview: forms.InputGroupDemo,
    source: formsSource,
  },
  {
    id: "form-field",
    name: "Form & field",
    description:
      "Native submission with inline validation and a recovery path.",
    category: "Inputs",
    Preview: forms.FormDemo,
    source: formsSource,
  },
  {
    id: "checkbox",
    name: "Checkbox",
    description: "An independent choice with checked and unchecked states.",
    category: "Inputs",
    Preview: forms.CheckboxDemo,
    source: formsSource,
  },
  {
    id: "checkbox-group-fieldset",
    name: "Checkbox group & fieldset",
    description: "Related choices share a visible group label.",
    category: "Inputs",
    Preview: forms.CheckboxGroupDemo,
    source: formsSource,
  },
  {
    id: "radio-group",
    name: "Radio group",
    description: "One choice from a named set.",
    category: "Inputs",
    Preview: forms.RadioDemo,
    source: formsSource,
  },
  {
    id: "switch",
    name: "Switch",
    description: "An immediate on or off setting.",
    category: "Inputs",
    Preview: forms.SwitchDemo,
    source: formsSource,
  },
  {
    id: "slider",
    name: "Slider",
    description: "A continuous value with keyboard adjustment.",
    category: "Inputs",
    Preview: forms.SliderDemo,
    source: formsSource,
  },
  {
    id: "number-field",
    name: "Number field",
    description: "A bounded value with increment and decrement actions.",
    category: "Inputs",
    Preview: forms.NumberDemo,
    source: formsSource,
  },
  {
    id: "input-otp",
    name: "Input OTP",
    description: "A six-digit code with ordered input labels.",
    category: "Inputs",
    Preview: forms.OTPDemo,
    source: formsSource,
  },
  {
    id: "combobox",
    name: "Combobox",
    description: "Search and select from known values.",
    category: "Inputs",
    Preview: forms.ComboboxDemo,
    source: formsSource,
  },
  {
    id: "autocomplete",
    name: "Autocomplete",
    description: "Suggestions that still allow a new value.",
    category: "Inputs",
    Preview: forms.AutocompleteDemo,
    source: formsSource,
  },
  {
    id: "command",
    name: "Command",
    description: "Search actions; execute only after explicit selection.",
    category: "Inputs",
    Preview: forms.CommandDemo,
    source: formsSource,
  },
  {
    id: "calendar",
    name: "Calendar",
    description:
      "Single, multiple, and range selection through the calendar API.",
    category: "Inputs",
    Preview: forms.CalendarDemo,
    source: formsSource,
  },
  {
    id: "dialog",
    name: "Dialog",
    description: "A focused modal with a title, description, and close action.",
    category: "Overlays",
    Preview: overlays.DialogDemo,
    source: overlaysSource,
  },
  {
    id: "alert-dialog",
    name: "Alert dialog",
    description: "A deliberate decision before a destructive action.",
    category: "Overlays",
    Preview: overlays.AlertDialogDemo,
    source: overlaysSource,
  },
  {
    id: "sheet",
    name: "Sheet",
    description: "Related detail in a side surface.",
    category: "Overlays",
    Preview: overlays.SheetDemo,
    source: overlaysSource,
  },
  {
    id: "drawer",
    name: "Drawer",
    description: "Focused actions in a bottom surface.",
    category: "Overlays",
    Preview: overlays.DrawerDemo,
    source: overlaysSource,
  },
  {
    id: "popover",
    name: "Popover",
    description: "Contextual controls anchored to a trigger.",
    category: "Overlays",
    Preview: overlays.PopoverDemo,
    source: overlaysSource,
  },
  {
    id: "tooltip",
    name: "Tooltip",
    description: "Brief help available on pointer hover and keyboard focus.",
    category: "Overlays",
    Preview: overlays.TooltipDemo,
    source: overlaysSource,
  },
  {
    id: "hover-card",
    name: "Hover card",
    description:
      "A preview of a link; essential information remains on the page.",
    category: "Overlays",
    Preview: overlays.PreviewCardDemo,
    source: overlaysSource,
  },
  {
    id: "dropdown-menu",
    name: "Dropdown menu",
    description: "A keyboard-navigable set of actions.",
    category: "Overlays",
    Preview: overlays.MenuDemo,
    source: overlaysSource,
  },
  {
    id: "context-menu",
    name: "Context menu",
    description: "Contextual actions, including a keyboard entry point.",
    category: "Overlays",
    Preview: overlays.ContextMenuDemo,
    source: overlaysSource,
  },
  {
    id: "select",
    name: "Select",
    description: "A finite selection with readable value labels.",
    category: "Overlays",
    Preview: overlays.SelectDemo,
    source: overlaysSource,
  },
  {
    id: "toast",
    name: "Toast",
    description: "A transient announcement with an explicit dismiss action.",
    category: "Overlays",
    Preview: overlays.ToastDemo,
    source: overlaysSource,
  },
  {
    id: "accordion",
    name: "Accordion",
    description: "Related disclosures with independently focusable headings.",
    category: "Navigation",
    Preview: navigation.AccordionDemo,
    source: navigationSource,
  },
  {
    id: "collapsible",
    name: "Collapsible",
    description: "Optional detail without leaving the current view.",
    category: "Navigation",
    Preview: navigation.CollapsibleDemo,
    source: navigationSource,
  },
  {
    id: "tabs",
    name: "Tabs",
    description: "Switch between sibling panels using pointer or arrow keys.",
    category: "Navigation",
    Preview: navigation.TabsDemo,
    source: navigationSource,
  },
  {
    id: "toggle",
    name: "Toggle",
    description: "An action that stays pressed until toggled again.",
    category: "Navigation",
    Preview: navigation.ToggleDemo,
    source: navigationSource,
  },
  {
    id: "toggle-group",
    name: "Toggle group",
    description: "A coordinated set of pressed choices.",
    category: "Navigation",
    Preview: navigation.ToggleGroupDemo,
    source: navigationSource,
  },
  {
    id: "toolbar",
    name: "Toolbar",
    description: "Related controls with shared keyboard navigation.",
    category: "Navigation",
    Preview: navigation.ToolbarDemo,
    source: navigationSource,
  },
  {
    id: "menubar",
    name: "Menubar",
    description: "Persistent menus for an application workspace.",
    category: "Navigation",
    Preview: navigation.MenubarDemo,
    source: navigationSource,
  },
  {
    id: "navigation-menu",
    name: "Navigation menu",
    description: "Links and nested destinations.",
    category: "Navigation",
    Preview: navigation.NavigationDemo,
    source: navigationSource,
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    description: "A location path with one current destination.",
    category: "Navigation",
    Preview: navigation.BreadcrumbDemo,
    source: navigationSource,
  },
  {
    id: "sidebar",
    name: "Sidebar",
    description: "A named set of primary destinations.",
    category: "Navigation",
    Preview: navigation.SidebarDemo,
    source: navigationSource,
  },
  {
    id: "pagination",
    name: "Pagination",
    description: "Bounded page navigation with explicit current state.",
    category: "Navigation",
    Preview: navigation.PaginationDemo,
    source: navigationSource,
  },
  {
    id: "card",
    name: "Card",
    description: "A contained widget or settings group.",
    category: "Display & layout",
    Preview: display.CardDemo,
    source: displaySource,
  },
  {
    id: "badge",
    name: "Badge",
    description: "Status expressed with text as well as color.",
    category: "Display & layout",
    Preview: display.BadgeDemo,
    source: displaySource,
  },
  {
    id: "alert",
    name: "Alert",
    description: "Inline information, success, warning, or failure.",
    category: "Display & layout",
    Preview: display.AlertDemo,
    source: displaySource,
  },
  {
    id: "avatar",
    name: "Avatar",
    description: "Identity with a deterministic fallback.",
    category: "Display & layout",
    Preview: display.AvatarDemo,
    source: displaySource,
  },
  {
    id: "progress",
    name: "Progress",
    description: "Completion of ongoing work.",
    category: "Display & layout",
    Preview: display.ProgressDemo,
    source: displaySource,
  },
  {
    id: "meter",
    name: "Meter",
    description: "A measurement in a known range.",
    category: "Display & layout",
    Preview: display.MeterDemo,
    source: displaySource,
  },
  {
    id: "skeleton",
    name: "Skeleton",
    description: "A decorative loading placeholder owned by its region.",
    category: "Display & layout",
    Preview: display.SkeletonDemo,
    source: displaySource,
  },
  {
    id: "spinner",
    name: "Spinner",
    description: "One named loading announcement.",
    category: "Display & layout",
    Preview: display.SpinnerDemo,
    source: displaySource,
  },
  {
    id: "empty-state",
    name: "Empty state",
    description: "Purpose and a useful next step.",
    category: "Display & layout",
    Preview: display.EmptyDemo,
    source: displaySource,
  },
  {
    id: "separator",
    name: "Separator",
    description: "A quiet boundary between related regions.",
    category: "Display & layout",
    Preview: display.SeparatorDemo,
    source: displaySource,
  },
  {
    id: "table",
    name: "Table",
    description: "Semantic rows with horizontal overflow on narrow screens.",
    category: "Display & layout",
    Preview: display.TableDemo,
    source: displaySource,
  },
  {
    id: "chart",
    name: "Chart",
    description: "Nonnegative categorical bars with readable table values.",
    category: "Display & layout",
    Preview: display.ChartDemo,
    source: displaySource,
  },
  {
    id: "aspect-ratio",
    name: "Aspect ratio",
    description: "A stable media frame without a layout shift.",
    category: "Display & layout",
    Preview: display.AspectRatioDemo,
    source: displaySource,
  },
  {
    id: "carousel",
    name: "Carousel",
    description: "Manual slide navigation with announced positions.",
    category: "Display & layout",
    Preview: display.CarouselDemo,
    source: displaySource,
  },
  {
    id: "scroll-area",
    name: "Scroll area",
    description: "A bounded region with accessible scrolling.",
    category: "Display & layout",
    Preview: display.ScrollAreaDemo,
    source: displaySource,
  },
  {
    id: "resizable",
    name: "Resizable",
    description: "Adjustable regions with pointer and keyboard controls.",
    category: "Display & layout",
    Preview: display.ResizableDemo,
    source: displaySource,
  },
];
