#!/usr/bin/env bash
#
# buzz_fleet_setup.sh — Initialize the Buzz relay for Doc2DB agent fleet comms.
#
# This script:
#   1. Verifies the relay is running and healthy
#   2. Generates Nostr keypairs for each fleet agent (if not already in .fleet_keys.env)
#   3. Adds all agents as relay members
#   4. Creates the coordination channels (fleet-coordination, cloud-dispatch, fleet-alerts)
#   5. Joins all agents to their relevant channels
#   6. Sends a bootstrap message from the coordinator
#
# Prerequisites:
#   - Buzz relay running on ws://localhost:3030
#   - Postgres on 127.0.0.1:15432 (isolated prototype)
#   - buzz-cli and buzz-admin built in target/release/
#
# Usage:
#   cd /home/davtan/code/buzz
#   ./scripts/buzz_fleet_setup.sh
#
set -euo pipefail

BUZZ_CLI="./target/release/buzz"
BUZZ_ADMIN="./target/release/buzz-admin"
RELAY_URL="${BUZZ_RELAY_URL:-ws://localhost:3030}"
DATABASE_URL="${DATABASE_URL:-postgres://buzz:buzz_dev@127.0.0.1:15432/buzz}"
KEYS_FILE=".fleet_keys.env"

echo "=== Buzz Fleet Setup ==="
echo "  Relay: $RELAY_URL"
echo "  Database: $DATABASE_URL"
echo ""

# 1. Health check
echo "--- Health check ---"
if ! curl -sf http://localhost:3030/health >/dev/null 2>&1; then
    echo "ERROR: Relay is not running on localhost:3030"
    echo "Start it with: DATABASE_URL=$DATABASE_URL ./target/release/buzz-relay"
    exit 1
fi
echo "Relay is healthy."
echo ""

# 2. Generate keys if needed
if [ ! -f "$KEYS_FILE" ]; then
    echo "--- Generating fleet keypairs ---"
    cat > "$KEYS_FILE" << 'KEYS_HEADER'
# Buzz fleet agent keypairs — generated by buzz_fleet_setup.sh
# DO NOT COMMIT THIS FILE
KEYS_HEADER

    generate_key() {
        local agent="$1"
        local pubvar="$(echo $agent | tr '[:lower:]' '[:upper:]' | tr '-' '_')_PUB"
        local keyvar="$(echo $agent | tr '[:lower:]' '[:upper:]' | tr '-' '_')_KEY"
        local output=$($BUZZ_ADMIN generate-key 2>&1)
        local pub=$(echo "$output" | grep "Public key:" | awk '{print $3}')
        local key=$(echo "$output" | grep "Secret key:" | awk '{print $3}')
        echo "BUZZ_${pubvar}=${pub}" >> "$KEYS_FILE"
        echo "BUZZ_${keyvar}=${key}" >> "$KEYS_FILE"
        echo "" >> "$KEYS_FILE"
        echo "  $agent: $pub"
    }

    for agent in coordinator codex-local claude-local hermes devin-cloud \
                 openclaw-rook openclaw-bishop openclaw-knight openclaw-pawn; do
        generate_key "$agent"
    done

    # Gitignore
    grep -q ".fleet_keys.env" .gitignore 2>/dev/null || echo ".fleet_keys.env" >> .gitignore
    echo "Keys saved to $KEYS_FILE (gitignored)"
else
    echo "Keys file $KEYS_FILE already exists — skipping key generation."
fi
echo ""

# Source the keys
source "$KEYS_FILE"

# 3. Add agents as relay members (direct SQL since admin needs relay signing key)
echo "--- Adding agents as relay members ---"
COMMUNITY_ID=$(PGPASSWORD=buzz_dev psql -h 127.0.0.1 -p 15432 -U buzz -d buzz -t -c \
    "SELECT id FROM communities WHERE host='127.0.0.1:3030' LIMIT 1;" 2>/dev/null | tr -d ' \n')

if [ -z "$COMMUNITY_ID" ]; then
    echo "WARNING: Could not find community for 127.0.0.1:3030 — agents may not be able to write."
    echo "Ensure the relay has started and seeded its community."
else
    for pub in "$BUZZ_COORDINATOR_PUB" "$BUZZ_CODEX_LOCAL_PUB" "$BUZZ_CLAUDE_LOCAL_PUB" \
               "$BUZZ_HERMES_PUB" "$BUZZ_DEVIN_CLOUD_PUB" \
               "$BUZZ_ROOK_PUB" "$BUZZ_BISHOP_PUB" \
               "$BUZZ_KNIGHT_PUB" "$BUZZ_PAWN_PUB"; do
        PGPASSWORD=buzz_dev psql -h 127.0.0.1 -p 15432 -U buzz -d buzz -c \
            "INSERT INTO relay_members (community_id, pubkey, role) VALUES ('$COMMUNITY_ID', '$pub', 'member') ON CONFLICT DO NOTHING;" >/dev/null 2>&1
    done
    echo "All 9 agents added as relay members."
fi
echo ""

# 4. Create channels (idempotent — check if they exist first)
echo "--- Creating coordination channels ---"
export BUZZ_RELAY_URL="$RELAY_URL"
export BUZZ_PRIVATE_KEY="$BUZZ_COORDINATOR_KEY"

create_channel() {
    local name="$1"
    local desc="$2"
    local existing=$($BUZZ_CLI --format compact channels list 2>/dev/null | python3 -c \
        "import sys,json; channels=json.load(sys.stdin); print(next((c['channel_id'] for c in channels if c.get('name')=='$name'), ''))" 2>/dev/null)
    if [ -n "$existing" ]; then
        echo "  $name: already exists ($existing)" >&2
        echo "$existing"
    else
        local result=$($BUZZ_CLI channels create --name "$name" --type stream --visibility open --description "$desc" 2>&1)
        local id=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin).get('channel_id',''))" 2>/dev/null)
        echo "  $name: created ($id)" >&2
        echo "$id"
    fi
}

COORD_CHANNEL=$(create_channel "fleet-coordination" "Main coordination channel for Doc2DB agent fleet")
CLOUD_CHANNEL=$(create_channel "cloud-dispatch" "Cloud Devin session coordination")
ALERT_CHANNEL=$(create_channel "fleet-alerts" "Fleet health alerts")

# Save channel IDs
cat > .fleet_channels.env << CHANNELS_EOF
# Buzz fleet channel IDs — generated by buzz_fleet_setup.sh
FLEET_COORD_CHANNEL=$COORD_CHANNEL
CLOUD_DISPATCH_CHANNEL=$CLOUD_CHANNEL
FLEET_ALERTS_CHANNEL=$ALERT_CHANNEL
CHANNELS_EOF
grep -q ".fleet_channels.env" .gitignore 2>/dev/null || echo ".fleet_channels.env" >> .gitignore
echo "Channel IDs saved to .fleet_channels.env"
echo ""

# 5. Join all agents to channels
echo "--- Joining agents to channels ---"
source .fleet_channels.env

join_channels() {
    local agent_key="$1"
    shift
    export BUZZ_PRIVATE_KEY="$agent_key"
    for ch in "$@"; do
        $BUZZ_CLI channels join --channel "$ch" >/dev/null 2>&1
    done
}

# All agents join fleet-coordination
for key_var in BUZZ_COORDINATOR_KEY BUZZ_CODEX_LOCAL_KEY BUZZ_CLAUDE_LOCAL_KEY \
               BUZZ_HERMES_KEY BUZZ_DEVIN_CLOUD_KEY \
               BUZZ_ROOK_KEY BUZZ_BISHOP_KEY \
               BUZZ_KNIGHT_KEY BUZZ_PAWN_KEY; do
    join_channels "${!key_var}" "$FLEET_COORD_CHANNEL"
done

# Coordinator, codex, claude, devin-cloud join cloud-dispatch
for key_var in BUZZ_COORDINATOR_KEY BUZZ_CODEX_LOCAL_KEY BUZZ_CLAUDE_LOCAL_KEY BUZZ_DEVIN_CLOUD_KEY; do
    join_channels "${!key_var}" "$CLOUD_DISPATCH_CHANNEL"
done

# All agents join fleet-alerts
for key_var in BUZZ_COORDINATOR_KEY BUZZ_HERMES_KEY \
               BUZZ_ROOK_KEY BUZZ_BISHOP_KEY \
               BUZZ_KNIGHT_KEY BUZZ_PAWN_KEY; do
    join_channels "${!key_var}" "$FLEET_ALERTS_CHANNEL"
done

echo "All agents joined to channels."
echo ""

# 6. Bootstrap message from coordinator
echo "--- Sending bootstrap message ---"
export BUZZ_PRIVATE_KEY="$BUZZ_COORDINATOR_KEY"
$BUZZ_CLI messages send \
    --channel "$FLEET_COORD_CHANNEL" \
    --content "Fleet coordination channel initialized. All agents online. Relay: $RELAY_URL" 2>&1 | python3 -c \
    "import sys,json; d=json.load(sys.stdin); print(f'Bootstrap message sent: {d.get(\"event_id\",\"\")}')" 2>/dev/null

echo ""
echo "=== Fleet setup complete ==="
echo ""
echo "Channels:"
echo "  fleet-coordination: $FLEET_COORD_CHANNEL"
echo "  cloud-dispatch:     $CLOUD_DISPATCH_CHANNEL"
echo "  fleet-alerts:       $FLEET_ALERTS_CHANNEL"
echo ""
echo "To send a message as an agent:"
echo "  export BUZZ_RELAY_URL=$RELAY_URL"
echo "  export BUZZ_PRIVATE_KEY=<agent_secret_key>"
echo "  $BUZZ_CLI messages send --channel <channel_id> --content 'hello fleet'"
