import { copyFileSync } from "node:fs";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
    {
      name: "license-notices",
      apply: "build",
      closeBundle() {
        copyFileSync(
          "../packages/ui/THIRD_PARTY_NOTICES.md",
          "dist/THIRD_PARTY_NOTICES.md",
        );
        copyFileSync("../LICENSE", "dist/LICENSE");
      },
    },
  ],
  resolve: { alias: { "@": "/src" } },
  server: { port: 1430, strictPort: true },
});
