//! Host-signed collaboration envelopes for Develop Helper fusion tools.
//!
//! Production signing happens after a Nostr event is admitted and before the
//! model prompt is built. The collaboration MCP verifies the same HMAC and
//! never accepts principals, roles, or project IDs from tool arguments.
//!
//! This module does not talk to `buzz-dev-mcp`. The HMAC key is generated by
//! the ACP process and given only to the `collab-mcp` sidecar.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{SystemTime, UNIX_EPOCH};

use hmac::{Hmac, KeyInit, Mac};
use serde::{Deserialize, Serialize};
use serde_json::{json, Map, Value};
use sha2::Sha256;

use crate::queue::{parse_thread_tags, BatchEvent};
use nostr::Event;

const SCHEMA_VERSION: u32 = 1;
const MAX_LIFETIME_SECONDS: u64 = 300;
const PROVIDER: &str = "buzz";
pub const DEFAULT_AGENT_AUTHORITY: &str = "buzz-agent:local";

type HmacSha256 = Hmac<Sha256>;

pub const HMAC_KEY_ENV: &str = "BUZZ_COLLAB_HMAC_KEY";
pub const TURN_PATH_ENV: &str = "BUZZ_COLLAB_TURN_PATH";
pub const HELPER_ROOT_ENV: &str = "BUZZ_COLLAB_HELPER_ROOT";
pub const AGENT_PRINCIPAL_ENV: &str = "BUZZ_COLLAB_AGENT_PRINCIPAL";
pub const AGENT_AUTHORITY_ENV: &str = "BUZZ_COLLAB_AGENT_AUTHORITY";
pub const ROLE_ENV: &str = "BUZZ_COLLAB_ROLE";

const READ_TOOLS: &[&str] = &[
    "artifact.inspect",
    "artifact.preview-register",
    "collaboration.inspect",
];
const MAIN_TOOLS: &[&str] = &[
    "artifact.register",
    "confirmation.confirm-current",
    "handoff.prepare",
    "handoff.record-sent",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum CollabRole {
    #[default]
    Unset,
    Main,
    Requirements,
    Solution,
    Ui,
    Recipient,
}

impl CollabRole {
    pub fn parse(value: &str) -> Self {
        match value.trim().to_ascii_lowercase().as_str() {
            "main" => Self::Main,
            "requirements" => Self::Requirements,
            "solution" => Self::Solution,
            "ui" => Self::Ui,
            "recipient" => Self::Recipient,
            _ => Self::Unset,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Unset => "",
            Self::Main => "main",
            Self::Requirements => "requirements",
            Self::Solution => "solution",
            Self::Ui => "ui",
            Self::Recipient => "recipient",
        }
    }

    pub fn is_unset(self) -> bool {
        matches!(self, Self::Unset)
    }

    pub fn tool_ceiling(self) -> &'static [&'static str] {
        match self {
            Self::Unset => &[],
            Self::Main => MAIN_AND_READ,
            Self::Requirements => REQUIREMENTS_AND_READ,
            Self::Solution | Self::Ui => READ_TOOLS,
            Self::Recipient => RECIPIENT_AND_READ,
        }
    }
}

const MAIN_AND_READ: &[&str] = &[
    "artifact.inspect",
    "artifact.preview-register",
    "collaboration.inspect",
    "artifact.register",
    "confirmation.confirm-current",
    "handoff.prepare",
    "handoff.record-sent",
];
const REQUIREMENTS_AND_READ: &[&str] = &[
    "artifact.inspect",
    "artifact.preview-register",
    "collaboration.inspect",
    "requirements.context",
    "requirements.save-draft",
];
const RECIPIENT_AND_READ: &[&str] = &[
    "artifact.inspect",
    "artifact.preview-register",
    "collaboration.inspect",
    "handoff.verify-receipt",
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecipientBinding {
    pub principal_id: String,
    pub authority: String,
}

#[derive(Debug, Clone)]
pub struct CollabHostConfig {
    pub role: CollabRole,
    /// Allowlist. The current envelope still carries exactly one project ID,
    /// selected from the top-level thread's first declaration.
    pub project_ids: Vec<String>,
    pub helper_root: Option<PathBuf>,
    pub mcp_command: String,
    pub authority: String,
    pub hmac_key: Vec<u8>,
    pub turn_path: PathBuf,
    /// Bound project per NIP-10 root. Survives heartbeats; not taken from
    /// `project_ids[0]`.
    pub thread_projects: Arc<Mutex<HashMap<String, String>>>,
}

impl Default for CollabHostConfig {
    fn default() -> Self {
        Self {
            role: CollabRole::Unset,
            project_ids: Vec::new(),
            helper_root: None,
            mcp_command: String::new(),
            authority: "buzz-desktop".into(),
            hmac_key: vec![0; 32],
            turn_path: PathBuf::new(),
            thread_projects: Arc::new(Mutex::new(HashMap::new())),
        }
    }
}

impl CollabHostConfig {
    pub fn is_active(&self) -> bool {
        !self.role.is_unset()
            && !self.project_ids.is_empty()
            && self.hmac_key.len() >= 32
            && !self.turn_path.as_os_str().is_empty()
            && self.helper_root.is_some()
    }
}

pub fn is_project_id(value: &str) -> bool {
    let bytes = value.as_bytes();
    if bytes.is_empty() || bytes.len() > 64 {
        return false;
    }
    let first = bytes[0];
    if !first.is_ascii_lowercase() && !first.is_ascii_digit() {
        return false;
    }
    bytes
        .iter()
        .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || *byte == b'-')
}

/// Dedicated line slots: `project_id=id`, `project_id:id`, or `project_id：id`.
pub fn declared_project_ids(statement: &str) -> Result<Vec<String>, String> {
    let mut ids = Vec::new();
    for line in statement.lines() {
        let line = line.trim();
        if line.is_empty() || !line.to_ascii_lowercase().starts_with("project_id") {
            continue;
        }
        let rest = line["project_id".len()..].trim_start();
        let Some(sep) = rest.chars().next() else {
            return Err("project_id 槽位不完整".into());
        };
        if sep != '=' && sep != ':' && sep != '：' {
            return Err("project_id 槽位不完整".into());
        }
        let id = rest[sep.len_utf8()..].trim();
        if !is_project_id(id) {
            return Err("项目 ID 格式无效".into());
        }
        if !ids.iter().any(|existing| existing == id) {
            ids.push(id.to_string());
        }
    }
    if ids.len() > 1 {
        return Err("一条消息不能声明多个项目".into());
    }
    Ok(ids)
}

pub fn resolve_thread_project(
    statement: &str,
    root_event_id: &str,
    is_root: bool,
    allowlist: &[String],
    bindings: &Arc<Mutex<HashMap<String, String>>>,
) -> Result<String, String> {
    let declared = declared_project_ids(statement)?;
    let declared = declared.into_iter().next();
    let mut map = bindings
        .lock()
        .map_err(|_| "协作项目绑定锁损坏".to_string())?;
    let bound = map.get(root_event_id).cloned();
    let require_allowed = |project_id: &str| {
        if allowlist.iter().any(|item| item == project_id) {
            Ok(())
        } else {
            Err("当前线程项目不在宿主允许名单内".to_string())
        }
    };
    match (declared.as_deref(), bound.as_deref(), is_root) {
        (Some(id), Some(existing), _) if id == existing => {
            require_allowed(id)?;
            Ok(id.to_string())
        }
        (Some(_), Some(_), _) => Err("不能在同一线程切换项目".into()),
        (Some(id), None, true) => {
            require_allowed(id)?;
            map.insert(root_event_id.to_string(), id.to_string());
            Ok(id.to_string())
        }
        (Some(_), None, false) => {
            Err("线程尚未绑定项目，不能从回复签发协作信封".into())
        }
        (None, Some(existing), _) => {
            require_allowed(existing)?;
            Ok(existing.to_string())
        }
        (None, None, _) => Err("宿主未从当前线程选定项目，不能签发协作信封".into()),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SignedEnvelope {
    pub payload: Value,
    pub signature: String,
}

#[derive(Debug, Clone)]
pub struct TurnClaim {
    pub project_id: String,
    pub agent_principal_id: String,
    pub agent_authority: String,
    pub agent_role: CollabRole,
    pub channel_id: String,
    pub session_id: String,
    pub root_event_id: String,
    pub event_id: String,
    pub user_principal_id: String,
    pub event_time: String,
    pub statement: String,
    pub recipient: Option<RecipientBinding>,
}

pub fn generate_hmac_key() -> Vec<u8> {
    nostr::Keys::generate()
        .secret_key()
        .as_secret_bytes()
        .to_vec()
}

pub fn canonical_payload(payload: &Value) -> Result<Vec<u8>, String> {
    let canonical = sort_value(payload);
    serde_json::to_vec(&canonical).map_err(|error| error.to_string())
}

fn sort_value(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut sorted = Map::new();
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            for key in keys {
                sorted.insert(key.clone(), sort_value(&map[key]));
            }
            Value::Object(sorted)
        }
        Value::Array(items) => Value::Array(items.iter().map(sort_value).collect()),
        other => other.clone(),
    }
}

pub fn sign_payload(hmac_key: &[u8], payload: &Value) -> Result<SignedEnvelope, String> {
    if hmac_key.len() < 32 {
        return Err("宿主上下文验签密钥至少需要 32 字节".into());
    }
    let mut mac =
        HmacSha256::new_from_slice(hmac_key).map_err(|error| error.to_string())?;
    mac.update(&canonical_payload(payload)?);
    Ok(SignedEnvelope {
        payload: payload.clone(),
        signature: hex::encode(mac.finalize().into_bytes()),
    })
}

pub fn verify_payload(
    hmac_key: &[u8],
    envelope: &SignedEnvelope,
    expected: &TurnClaim,
) -> Result<(), String> {
    let signed = sign_payload(hmac_key, &envelope.payload)?;
    if !constant_time_eq(&signed.signature, &envelope.signature) {
        return Err("宿主事件签名不匹配".into());
    }
    let payload = envelope
        .payload
        .as_object()
        .ok_or("宿主事件声明字段不完整")?;
    require_str(payload, "provider", PROVIDER)?;
    require_str(payload, "agent_principal_id", &expected.agent_principal_id)?;
    require_str(payload, "agent_authority", &expected.agent_authority)?;
    require_str(payload, "project_id", &expected.project_id)?;
    require_str(payload, "channel_id", &expected.channel_id)?;
    require_str(payload, "session_id", &expected.session_id)?;
    require_str(payload, "root_event_id", &expected.root_event_id)?;
    require_str(payload, "event_id", &expected.event_id)?;
    require_str(payload, "user_principal_id", &expected.user_principal_id)?;
    require_str(payload, "agent_role", expected.agent_role.as_str())?;
    Ok(())
}

fn constant_time_eq(left: &str, right: &str) -> bool {
    left.len() == right.len()
        && left
            .as_bytes()
            .iter()
            .zip(right.as_bytes())
            .fold(0, |acc, (a, b)| acc | (a ^ b))
            == 0
}

fn require_str(payload: &Map<String, Value>, field: &str, expected: &str) -> Result<(), String> {
    match payload.get(field).and_then(Value::as_str) {
        Some(actual) if actual == expected => Ok(()),
        _ => Err(format!("宿主事件与当前调用边界不匹配：{field}")),
    }
}

pub fn tools_for_turn(role: CollabRole, recipient: Option<&RecipientBinding>) -> Vec<String> {
    let mut tools: Vec<String> = role
        .tool_ceiling()
        .iter()
        .map(|tool| (*tool).to_string())
        .collect();
    if recipient.is_none() {
        tools.retain(|tool| tool != "handoff.prepare" && tool != "handoff.record-sent");
    }
    if role != CollabRole::Recipient {
        tools.retain(|tool| tool != "handoff.verify-receipt");
    }
    tools
}

/// Other `p` tags besides the current agent. Zero or more than one → none.
pub fn select_recipient(
    mentioned_pubkeys: &[String],
    agent_principal_hex: &str,
    agent_authority: &str,
) -> Option<RecipientBinding> {
    let mut others: Vec<String> = mentioned_pubkeys
        .iter()
        .map(|value| value.trim().to_ascii_lowercase())
        .filter(|value| !value.is_empty() && value != &agent_principal_hex.to_ascii_lowercase())
        .collect();
    others.sort();
    others.dedup();
    match others.as_slice() {
        [principal_id] => Some(RecipientBinding {
            principal_id: principal_id.clone(),
            authority: agent_authority.to_string(),
        }),
        _ => None,
    }
}

pub fn root_event_id(event: &Event) -> String {
    parse_thread_tags(event)
        .root_event_id
        .unwrap_or_else(|| event.id.to_hex())
}

pub fn claim_from_admitted_event(
    event: &Event,
    session_id: &str,
    config: &CollabHostConfig,
    agent_principal_id: &str,
) -> Result<TurnClaim, String> {
    if config.role.is_unset() {
        return Err("宿主未绑定协作角色".into());
    }
    if config.project_ids.is_empty() {
        return Err("宿主未绑定可管理项目，不能签发协作信封".into());
    }
    let tags = parse_thread_tags(event);
    let root = root_event_id(event);
    let project_id = resolve_thread_project(
        &event.content,
        &root,
        root == event.id.to_hex(),
        &config.project_ids,
        &config.thread_projects,
    )?;
    let recipient = select_recipient(
        &tags.mentioned_pubkeys,
        agent_principal_id,
        DEFAULT_AGENT_AUTHORITY,
    );
    let created = chrono::DateTime::<chrono::Utc>::from_timestamp(event.created_at.as_secs() as i64, 0)
        .ok_or("事件时间无效")?;
    Ok(TurnClaim {
        project_id,
        agent_principal_id: agent_principal_id.to_string(),
        agent_authority: DEFAULT_AGENT_AUTHORITY.into(),
        agent_role: config.role,
        channel_id: event
            .tags
            .iter()
            .find_map(|tag| {
                let parts = tag.as_slice();
                (parts.len() >= 2 && parts[0] == "e").then(|| parts[1].clone())
            })
            .unwrap_or_else(|| event.id.to_hex()),
        session_id: session_id.to_string(),
        root_event_id: root,
        event_id: event.id.to_hex(),
        user_principal_id: event.pubkey.to_hex(),
        event_time: created.format("%Y-%m-%dT%H:%M:%SZ").to_string(),
        statement: event.content.clone(),
        recipient,
    })
}

/// Channel ID is carried on `QueuedEvent` / `FlushBatch`, not guessed from tags.
pub fn claim_from_batch_event(
    event: &Event,
    channel_id: &str,
    session_id: &str,
    config: &CollabHostConfig,
    agent_principal_id: &str,
) -> Result<TurnClaim, String> {
    let mut claim = claim_from_admitted_event(event, session_id, config, agent_principal_id)?;
    claim.channel_id = channel_id.to_string();
    Ok(claim)
}

pub fn envelope_from_claim(
    hmac_key: &[u8],
    authority: &str,
    claim: &TurnClaim,
    now_unix: u64,
    nonce: &str,
) -> Result<SignedEnvelope, String> {
    if nonce.len() != 32 || !nonce.chars().all(|ch| ch.is_ascii_hexdigit()) {
        return Err("宿主事件 nonce 无效".into());
    }
    let tools = tools_for_turn(claim.agent_role, claim.recipient.as_ref());
    if tools.iter().any(|tool| {
        MAIN_TOOLS.contains(&tool.as_str()) && claim.agent_role != CollabRole::Main
    }) {
        return Err("宿主为当前角色签发了越权工具".into());
    }
    let recipient = match &claim.recipient {
        Some(binding) => json!({
            "principal_id": binding.principal_id,
            "authority": binding.authority,
        }),
        None => Value::Null,
    };
    let payload = json!({
        "schema_version": SCHEMA_VERSION,
        "provider": PROVIDER,
        "authority": authority,
        "project_id": claim.project_id,
        "agent_principal_id": claim.agent_principal_id,
        "agent_authority": claim.agent_authority,
        "agent_role": claim.agent_role.as_str(),
        "channel_id": claim.channel_id,
        "session_id": claim.session_id,
        "root_event_id": claim.root_event_id,
        "event_id": claim.event_id,
        "user_principal_id": claim.user_principal_id,
        "event_time": claim.event_time,
        "statement": claim.statement,
        "recipient": recipient,
        "tools": tools,
        "issued_at": now_unix,
        "expires_at": now_unix + 100,
        "nonce": nonce,
    });
    if now_unix + 100 - now_unix > MAX_LIFETIME_SECONDS {
        return Err("宿主事件有效期无效或超过 5 分钟".into());
    }
    sign_payload(hmac_key, &payload)
}

pub fn random_nonce() -> String {
    hex::encode(&generate_hmac_key()[..16])
}

pub fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

#[derive(Clone, Default)]
pub struct CollabContextBroker {
    inner: Arc<Mutex<HashMap<(String, String), SignedEnvelope>>>,
}

impl CollabContextBroker {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn update(&self, agent_principal: &str, session_id: &str, envelope: SignedEnvelope) {
        self.inner
            .lock()
            .expect("collab broker lock")
            .insert(
                (agent_principal.to_string(), session_id.to_string()),
                envelope,
            );
    }

    #[cfg(test)]
    pub fn get(&self, agent_principal: &str, session_id: &str) -> Option<SignedEnvelope> {
        self.inner
            .lock()
            .expect("collab broker lock")
            .get(&(agent_principal.to_string(), session_id.to_string()))
            .cloned()
    }

    pub fn clear(&self, agent_principal: &str, session_id: &str) {
        self.inner
            .lock()
            .expect("collab broker lock")
            .remove(&(agent_principal.to_string(), session_id.to_string()));
    }

    pub fn write_turn_file(path: &Path, envelope: &SignedEnvelope) -> Result<(), String> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|error| error.to_string())?;
        }
        let body = serde_json::to_vec(envelope).map_err(|error| error.to_string())?;
        let tmp = path.with_extension("json.tmp");
        std::fs::write(&tmp, body).map_err(|error| error.to_string())?;
        std::fs::rename(&tmp, path).map_err(|error| error.to_string())?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut permissions = std::fs::metadata(path)
                .map_err(|error| error.to_string())?
                .permissions();
            permissions.set_mode(0o600);
            std::fs::set_permissions(path, permissions).map_err(|error| error.to_string())?;
        }
        Ok(())
    }
}

pub fn publish_turn(
    broker: &CollabContextBroker,
    config: &CollabHostConfig,
    agent_principal: &str,
    session_id: &str,
    envelope: SignedEnvelope,
) -> Result<(), String> {
    broker.update(agent_principal, session_id, envelope.clone());
    CollabContextBroker::write_turn_file(&config.turn_path, &envelope)
}

pub fn clear_turn(path: &Path) -> Result<(), String> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error.to_string()),
    }
}

/// Sign and publish the current channel turn, or drop stale context on heartbeat.
/// Active collaboration that cannot select a thread project refuses and clears
/// the previous turn rather than leaving a confirmation capability in place.
pub fn publish_prompt_turn(
    broker: &CollabContextBroker,
    config: &CollabHostConfig,
    agent_principal: &str,
    session_id: &str,
    channel_id: Option<&str>,
    events: &[BatchEvent],
    cancelled_events: &[BatchEvent],
) -> Result<(), String> {
    if !config.is_active() {
        return Ok(());
    }
    let Some(channel_id) = channel_id else {
        broker.clear(agent_principal, session_id);
        return clear_turn(&config.turn_path);
    };
    let envelope = match envelope_for_batch(
        config,
        agent_principal,
        session_id,
        channel_id,
        events,
        cancelled_events,
    ) {
        Ok(envelope) => envelope,
        Err(error) => {
            broker.clear(agent_principal, session_id);
            let _ = clear_turn(&config.turn_path);
            return Err(error);
        }
    };
    publish_turn(broker, config, agent_principal, session_id, envelope)
}

pub fn envelope_for_batch(
    config: &CollabHostConfig,
    agent_principal: &str,
    session_id: &str,
    channel_id: &str,
    events: &[BatchEvent],
    cancelled_events: &[BatchEvent],
) -> Result<SignedEnvelope, String> {
    if events.len() != 1 || !cancelled_events.is_empty() {
        return Err("协作 turn 必须且只能包含一条已接纳事件".into());
    }
    let event = events
        .first()
        .map(|item| &item.event)
        .ok_or("当前批次没有已接纳事件")?;
    let claim = claim_from_batch_event(event, channel_id, session_id, config, agent_principal)?;
    envelope_from_claim(
        &config.hmac_key,
        &config.authority,
        &claim,
        now_unix(),
        &random_nonce(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use nostr::{Event, EventBuilder, Keys, Kind, Tag};
    use uuid::Uuid;

    const KEY: &[u8] = b"unit-05-host-context-verification-key";

    fn claim() -> TurnClaim {
        TurnClaim {
            project_id: "demo".into(),
            agent_principal_id: "main-1".into(),
            agent_authority: DEFAULT_AGENT_AUTHORITY.into(),
            agent_role: CollabRole::Main,
            channel_id: "channel-1".into(),
            session_id: "session-1".into(),
            root_event_id: "root-1".into(),
            event_id: "event-1".into(),
            user_principal_id: "user-1".into(),
            event_time: "2026-09-20T12:00:00Z".into(),
            statement: "check".into(),
            recipient: None,
        }
    }

    #[test]
    fn canonical_payload_matches_python_hmac_vector() {
        let payload = json!({
            "schema_version": 1,
            "provider": "buzz",
            "authority": "relay:local",
            "project_id": "demo",
            "agent_principal_id": "main-1",
            "agent_authority": "buzz-agent:local",
            "agent_role": "main",
            "channel_id": "channel-1",
            "session_id": "session-1",
            "root_event_id": "root-1",
            "event_id": "event-1",
            "user_principal_id": "user-1",
            "event_time": "2026-09-20T12:00:00Z",
            "statement": "check",
            "recipient": Value::Null,
            "tools": ["artifact.inspect"],
            "issued_at": 1_800_000_000_u64,
            "expires_at": 1_800_000_100_u64,
            "nonce": "1".repeat(32),
        });
        let envelope = sign_payload(KEY, &payload).expect("sign");
        assert_eq!(
            envelope.signature,
            "31f5c0c134b1252ebf7357e7287f75865649784cbaa7e7f7e65f2bc725035006"
        );
    }

    #[test]
    fn forged_role_or_event_fails_signature() {
        let envelope = envelope_from_claim(KEY, "relay:local", &claim(), 1_800_000_000, &"1".repeat(32))
            .expect("sign");
        let mut forged = envelope.clone();
        forged.payload["agent_role"] = json!("requirements");
        assert!(verify_payload(KEY, &forged, &claim()).is_err());
        let mut other_event = claim();
        other_event.event_id = "event-2".into();
        assert!(verify_payload(KEY, &envelope, &other_event).is_err());
    }

    #[test]
    fn worker_ceiling_excludes_main_tools() {
        let tools = tools_for_turn(CollabRole::Requirements, None);
        assert!(tools.contains(&"requirements.save-draft".into()));
        assert!(!tools.iter().any(|tool| MAIN_TOOLS.contains(&tool.as_str())));
    }

    #[test]
    fn handoff_tools_require_single_recipient() {
        let without = tools_for_turn(CollabRole::Main, None);
        assert!(!without.iter().any(|tool| tool.starts_with("handoff.")));
        let recipient = RecipientBinding {
            principal_id: "solution-1".into(),
            authority: DEFAULT_AGENT_AUTHORITY.into(),
        };
        let with = tools_for_turn(CollabRole::Main, Some(&recipient));
        assert!(with.contains(&"handoff.prepare".into()));
    }

    #[test]
    fn recipient_selection_does_not_guess_multiple_mentions() {
        let agent = "aa".repeat(32);
        let one = select_recipient(
            &[agent.clone(), "bb".repeat(32)],
            &agent,
            DEFAULT_AGENT_AUTHORITY,
        );
        assert_eq!(one.unwrap().principal_id, "bb".repeat(32));
        let many = select_recipient(
            &[agent.clone(), "bb".repeat(32), "cc".repeat(32)],
            &agent,
            DEFAULT_AGENT_AUTHORITY,
        );
        assert!(many.is_none());
    }

    fn signed_text_note(content: &str, tags: Vec<Tag>) -> Event {
        let keys = Keys::generate();
        EventBuilder::new(Kind::Custom(1), content)
            .tags(tags)
            .sign_with_keys(&keys)
            .expect("sign event")
    }

    #[test]
    fn top_level_event_uses_own_id_as_root() {
        let event = signed_text_note("hello", vec![]);
        assert_eq!(root_event_id(&event), event.id.to_hex());
    }

    #[test]
    fn session_reuse_replaces_broker_context() {
        let broker = CollabContextBroker::new();
        let first = sign_payload(KEY, &json!({"event_id": "old"})).unwrap();
        let second = sign_payload(KEY, &json!({"event_id": "new"})).unwrap();
        broker.update("agent", "session-1", first);
        broker.update("agent", "session-1", second.clone());
        assert_eq!(
            broker.get("agent", "session-1").unwrap().payload["event_id"],
            json!("new")
        );
        assert_ne!(
            broker.get("agent", "session-1").unwrap().signature,
            sign_payload(KEY, &json!({"event_id": "old"}))
                .unwrap()
                .signature
        );
        let _ = second;
    }

    #[test]
    fn allowlist_without_thread_declaration_refuses_to_issue() {
        let config = CollabHostConfig {
            role: CollabRole::Main,
            project_ids: vec!["a".into(), "b".into()],
            hmac_key: KEY.to_vec(),
            ..CollabHostConfig::default()
        };
        let event = signed_text_note("hello", vec![]);
        let error = claim_from_batch_event(
            &event,
            &Uuid::new_v4().to_string(),
            "session-1",
            &config,
            &event.pubkey.to_hex(),
        )
        .unwrap_err();
        assert!(error.contains("选定项目"), "{error}");
    }

    #[test]
    fn thread_declaration_selects_allowlisted_project() {
        let config = CollabHostConfig {
            role: CollabRole::Main,
            project_ids: vec!["demo".into(), "just-start".into()],
            hmac_key: KEY.to_vec(),
            ..CollabHostConfig::default()
        };
        let event = signed_text_note("@first-mate\nproject_id=just-start\n检查", vec![]);
        let claim = claim_from_batch_event(
            &event,
            &Uuid::new_v4().to_string(),
            "session-1",
            &config,
            &event.pubkey.to_hex(),
        )
        .expect("thread project");
        assert_eq!(claim.project_id, "just-start");
        assert_ne!(claim.project_id, config.project_ids[0]);
    }

    #[test]
    fn first_allowlist_item_is_not_used_without_declaration() {
        let config = CollabHostConfig {
            role: CollabRole::Main,
            project_ids: vec!["first".into(), "second".into()],
            hmac_key: KEY.to_vec(),
            ..CollabHostConfig::default()
        };
        let event = signed_text_note("no slot here", vec![]);
        assert!(claim_from_batch_event(
            &event,
            "channel-1",
            "session-1",
            &config,
            &event.pubkey.to_hex(),
        )
        .is_err());
    }

    #[test]
    fn out_of_allowlist_and_multiple_slots_are_rejected() {
        let config = CollabHostConfig {
            role: CollabRole::Main,
            project_ids: vec!["demo".into(), "other".into()],
            hmac_key: KEY.to_vec(),
            ..CollabHostConfig::default()
        };
        let outside = signed_text_note("project_id=secret", vec![]);
        let outside_error = claim_from_batch_event(
            &outside,
            "channel-1",
            "session-1",
            &config,
            &outside.pubkey.to_hex(),
        )
        .unwrap_err();
        assert!(outside_error.contains("允许名单"), "{outside_error}");
        let many = signed_text_note("project_id=demo\nproject_id=other", vec![]);
        let many_error = claim_from_batch_event(
            &many,
            "channel-1",
            "session-1",
            &config,
            &many.pubkey.to_hex(),
        )
        .unwrap_err();
        assert!(many_error.contains("多个项目"), "{many_error}");
    }

    #[test]
    fn reply_keeps_root_binding_and_rejects_switch() {
        let config = CollabHostConfig {
            role: CollabRole::Main,
            project_ids: vec!["demo".into(), "other".into()],
            hmac_key: KEY.to_vec(),
            ..CollabHostConfig::default()
        };
        let root = signed_text_note("project_id=demo\nstart", vec![]);
        claim_from_batch_event(
            &root,
            "channel-1",
            "session-1",
            &config,
            &root.pubkey.to_hex(),
        )
        .expect("bind root");
        let reply_tags = vec![
            Tag::parse(["e", &root.id.to_hex(), "", "root"]).expect("root tag"),
            Tag::parse(["e", &root.id.to_hex(), "", "reply"]).expect("reply tag"),
        ];
        let same = signed_text_note("continue without repeating", reply_tags.clone());
        let claim = claim_from_batch_event(
            &same,
            "channel-1",
            "session-1",
            &config,
            &same.pubkey.to_hex(),
        )
        .expect("reuse binding");
        assert_eq!(claim.project_id, "demo");
        assert_eq!(claim.root_event_id, root.id.to_hex());
        let switched = signed_text_note("project_id=other", reply_tags);
        let error = claim_from_batch_event(
            &switched,
            "channel-1",
            "session-1",
            &config,
            &switched.pubkey.to_hex(),
        )
        .unwrap_err();
        assert!(error.contains("切换项目"), "{error}");
    }

    #[test]
    fn issue_failure_clears_previous_turn() {
        let dir = std::env::temp_dir().join(format!("buzz-collab-clear-{}", Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let turn_path = dir.join("turn.json");
        let config = CollabHostConfig {
            role: CollabRole::Main,
            project_ids: vec!["demo".into(), "other".into()],
            helper_root: Some(PathBuf::from("/tmp/helper")),
            hmac_key: KEY.to_vec(),
            turn_path: turn_path.clone(),
            ..CollabHostConfig::default()
        };
        let broker = CollabContextBroker::new();
        let first = signed_text_note("project_id=demo\nfirst", vec![]);
        let agent = first.pubkey.to_hex();
        publish_prompt_turn(
            &broker,
            &config,
            &agent,
            "session-1",
            Some("channel-1"),
            &[batch_event(first)],
            &[],
        )
        .unwrap();
        assert!(turn_path.exists());
        let bad = signed_text_note("project_id=secret", vec![]);
        let error = publish_prompt_turn(
            &broker,
            &config,
            &agent,
            "session-1",
            Some("channel-1"),
            &[batch_event(bad)],
            &[],
        )
        .unwrap_err();
        assert!(error.contains("允许名单"), "{error}");
        assert!(broker.get(&agent, "session-1").is_none());
        assert!(!turn_path.exists());
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn shell_env_must_not_carry_hmac_key() {
        assert_eq!(HMAC_KEY_ENV, "BUZZ_COLLAB_HMAC_KEY");
        assert_ne!(HMAC_KEY_ENV, "BUZZ_PRIVATE_KEY");
    }

    #[test]
    fn mixed_event_batch_is_rejected_before_the_last_event_can_authorize_it() {
        let config = active_config(PathBuf::from("/tmp/unused-turn.json"));
        let agent = Keys::generate().public_key().to_hex();
        let rejected = signed_text_note("project_id=secret\nreject me", vec![]);
        let allowed = signed_text_note("project_id=demo\nallow me", vec![]);
        let error = envelope_for_batch(
            &config,
            &agent,
            "session-1",
            "channel-1",
            &[batch_event(rejected), batch_event(allowed)],
            &[],
        )
        .unwrap_err();
        assert!(error.contains("只能包含一条"), "{error}");
        assert!(config.thread_projects.lock().unwrap().is_empty());
    }

    #[test]
    fn cancelled_event_cannot_share_a_collaboration_turn() {
        let config = active_config(PathBuf::from("/tmp/unused-turn.json"));
        let agent = Keys::generate().public_key().to_hex();
        let current = signed_text_note("project_id=demo\ncurrent", vec![]);
        let cancelled = signed_text_note("project_id=demo\nprevious", vec![]);
        let error = envelope_for_batch(
            &config,
            &agent,
            "session-1",
            "channel-1",
            &[batch_event(current)],
            &[batch_event(cancelled)],
        )
        .unwrap_err();
        assert!(error.contains("只能包含一条"), "{error}");
    }

    fn batch_event(event: Event) -> BatchEvent {
        BatchEvent {
            event,
            prompt_tag: String::new(),
            received_at: std::time::Instant::now(),
        }
    }

    fn active_config(turn_path: PathBuf) -> CollabHostConfig {
        CollabHostConfig {
            role: CollabRole::Main,
            project_ids: vec!["demo".into()],
            helper_root: Some(PathBuf::from("/tmp/helper")),
            hmac_key: KEY.to_vec(),
            turn_path,
            ..CollabHostConfig::default()
        }
    }

    #[test]
    fn session_reuse_replaces_turn_file_and_heartbeat_clears_it() {
        let dir = std::env::temp_dir().join(format!("buzz-collab-test-{}", Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let turn_path = dir.join("turn.json");
        let config = active_config(turn_path.clone());
        let broker = CollabContextBroker::new();
        let first = signed_text_note("project_id=demo\nfirst", vec![]);
        let agent = first.pubkey.to_hex();
        publish_prompt_turn(
            &broker,
            &config,
            &agent,
            "session-1",
            Some("channel-1"),
            &[batch_event(first.clone())],
            &[],
        )
        .unwrap();
        let first_id = broker.get(&agent, "session-1").unwrap().payload["event_id"].clone();
        let second = signed_text_note("project_id=demo\nsecond", vec![]);
        publish_prompt_turn(
            &broker,
            &config,
            &agent,
            "session-1",
            Some("channel-1"),
            &[batch_event(second.clone())],
            &[],
        )
        .unwrap();
        let updated = broker.get(&agent, "session-1").unwrap();
        assert_eq!(updated.payload["event_id"], json!(second.id.to_hex()));
        assert_ne!(updated.payload["event_id"], first_id);
        let on_disk: SignedEnvelope =
            serde_json::from_slice(&std::fs::read(&turn_path).unwrap()).unwrap();
        assert_eq!(on_disk.payload["event_id"], json!(second.id.to_hex()));
        publish_prompt_turn(&broker, &config, &agent, "session-1", None, &[], &[]).unwrap();
        assert!(broker.get(&agent, "session-1").is_none());
        assert!(!turn_path.exists());
        let _ = std::fs::remove_dir_all(dir);
    }
}
