import type {
  AgentActivityDescriptor,
  TranscriptItem,
} from "./agentSessionTypes";

const sessionId = "debug-session-render-classes";
const turnId = "debug-turn-render-classes";
const channelId = "debug-channel-render-classes";
const userPubkey = "debug-user-render-classes";
const baseTimestamp = Date.parse("2026-06-30T00:00:00.000Z");

function timestamp(seconds: number) {
  return new Date(baseTimestamp + seconds * 1000).toISOString();
}

function descriptor(
  renderClass: AgentActivityDescriptor["renderClass"],
  label: string,
  preview: string | null,
  groupKey: string,
  options: Partial<AgentActivityDescriptor> = {},
): AgentActivityDescriptor {
  return {
    renderClass,
    label,
    preview,
    source: "fallback",
    groupKey,
    ...options,
  };
}

/**
 * Temporary design-debug fixture: one coherent turn that exercises every
 * AgentActivityRenderClass and every TranscriptItem variant. Keep this isolated
 * so it can be removed surgically before the PR merges.
 */
export const DEBUG_AGENT_ACTIVITY_FIXTURE: TranscriptItem[] = [
  {
    id: "debug:turn-started",
    type: "lifecycle",
    renderClass: "status",
    title: "Turn started",
    text: "Triggered by 1 event.",
    timestamp: timestamp(0),
    acpSource: "turn_started",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:session-resolved",
    type: "lifecycle",
    renderClass: "status",
    title: "Session ready",
    text: "Observer attached to the local agent session.",
    timestamp: timestamp(1),
    acpSource: "session_resolved",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:user-prompt",
    type: "message",
    renderClass: "message",
    role: "user",
    title: "Taylor Ho",
    text: "@Agent audit the activity feed taxonomy and show me the risky spots before you edit.",
    timestamp: timestamp(2),
    acpSource: "session/prompt:user",
    authorPubkey: userPubkey,
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:prompt-context",
    type: "metadata",
    renderClass: "raw-rail",
    title: "Prompt context",
    sections: [
      {
        title: "Channel",
        body: "buzz-agent-observability · live agent activity thread",
      },
      {
        title: "Recent directive",
        body: "Keep the UI honest: reasoning, messages, shell output, relay operations, and raw ACP payloads stay distinct.",
      },
    ],
    timestamp: timestamp(2.2),
    acpSource: "session/prompt:context",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:thought",
    type: "thought",
    renderClass: "thought",
    title: "Thinking",
    text: "I need to inspect the existing taxonomy, verify the render classes, then make the smallest safe change. Shell stdout is evidence, not reasoning.",
    timestamp: timestamp(4),
    acpSource: "agent_thought_chunk",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:plan",
    type: "plan",
    renderClass: "plan",
    title: "Plan updated",
    text: "1. Read the transcript components.\n2. Classify the observed tools.\n3. Patch the Activity header.\n4. Run desktop gates and report the pushed SHA.",
    timestamp: timestamp(5),
    acpSource: "plan",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:status",
    type: "lifecycle",
    renderClass: "status",
    title: "Observer connected",
    text: "Streaming normalized ACP activity.",
    timestamp: timestamp(6),
    acpSource: "observer_connected",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:shell-tool",
    type: "tool",
    renderClass: "shell",
    descriptor: descriptor(
      "shell",
      "Ran command",
      "git status --short",
      "shell:command",
      {
        operation: "shell",
        source: "harness",
      },
    ),
    title: "Shell",
    toolName: "buzz-dev-mcp__shell",
    buzzToolName: null,
    status: "completed",
    args: { command: "git status --short" },
    result: "## tho/activity-feed-rebuild...origin/main [ahead 4]\n",
    isError: false,
    timestamp: timestamp(8),
    startedAt: timestamp(8),
    completedAt: timestamp(9),
    acpSource: "tool_call_update",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:relay-op-tool",
    type: "tool",
    renderClass: "relay-op",
    descriptor: descriptor(
      "relay-op",
      "Channels Get",
      "buzz-agent-observability",
      "buzz-cli:channels.get",
      {
        operation: "channels.get",
        object: "buzz-agent-observability",
        source: "shell",
        tone: "read",
      },
    ),
    title: "buzz channels get",
    toolName: "shell",
    buzzToolName: null,
    status: "completed",
    args: { command: "buzz channels get --channel buzz-agent-observability" },
    result: '{"name":"buzz-agent-observability","members":7}',
    isError: false,
    timestamp: timestamp(10),
    startedAt: timestamp(10),
    completedAt: timestamp(11),
    acpSource: "tool_call_update",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:message-tool",
    type: "tool",
    renderClass: "message",
    descriptor: descriptor(
      "message",
      "Send Message",
      "@Ned picked it up — testing the full taxonomy now.",
      "buzz-cli:messages.send",
      {
        operation: "messages.send",
        object: "@Ned picked it up — testing the full taxonomy now.",
        source: "shell",
        tone: "write",
      },
    ),
    title: "buzz messages send",
    toolName: "shell",
    buzzToolName: null,
    status: "completed",
    args: {
      command:
        'buzz messages send --channel buzz-agent-observability --content "@Ned picked it up — testing the full taxonomy now."',
    },
    result: '{"accepted":true,"event_id":"debug-event"}',
    isError: false,
    timestamp: timestamp(12),
    startedAt: timestamp(12),
    completedAt: timestamp(13),
    acpSource: "tool_call_update",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:file-edit-tool",
    type: "tool",
    renderClass: "file-edit",
    descriptor: descriptor(
      "file-edit",
      "Edited file",
      "desktop/src/features/channels/ui/AgentSessionThreadPanel.tsx",
      "file-edit:str_replace",
      {
        operation: "str_replace",
        object: "desktop/src/features/channels/ui/AgentSessionThreadPanel.tsx",
        source: "harness",
        tone: "write",
      },
    ),
    title: "str_replace",
    toolName: "str_replace",
    buzzToolName: null,
    status: "completed",
    args: {
      path: "desktop/src/features/channels/ui/AgentSessionThreadPanel.tsx",
      old_str: "<Switch />",
      new_str: "<DropdownMenuCheckboxItem />",
    },
    result: "Replaced 1 occurrence.",
    isError: false,
    timestamp: timestamp(14),
    startedAt: timestamp(14),
    completedAt: timestamp(15),
    acpSource: "tool_call_update",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:permission",
    type: "lifecycle",
    renderClass: "permission",
    title: "Permission requested",
    text: "Confirm force-with-lease push to block/buzz.",
    timestamp: timestamp(16),
    descriptor: descriptor(
      "permission",
      "Permission requested",
      "force-with-lease push",
      "permission:git-push",
      {
        source: "acp",
        tone: "admin",
      },
    ),
    acpSource: "permission_request",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:generic-tool",
    type: "tool",
    renderClass: "generic",
    descriptor: descriptor(
      "generic",
      "Ran tool",
      "resolve-worktree-context",
      "generic:resolve_worktree_context",
      {
        operation: "resolve_worktree_context",
        source: "fallback",
      },
    ),
    title: "resolve-worktree-context",
    toolName: "resolve_worktree_context",
    buzzToolName: null,
    status: "completed",
    args: { worktree: "~/.buzz/REPOS/buzz-pr-3-activity-feed-rebuild" },
    result: "branch=tho/activity-feed-rebuild clean=true",
    isError: false,
    timestamp: timestamp(17),
    startedAt: timestamp(17),
    completedAt: timestamp(18),
    acpSource: "tool_call_update",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:error-tool",
    type: "tool",
    renderClass: "error",
    descriptor: descriptor(
      "error",
      "Command failed",
      "pnpm --dir desktop test -- --runInBand",
      "error:shell",
      {
        operation: "shell",
        source: "harness",
      },
    ),
    title: "Shell",
    toolName: "shell",
    buzzToolName: null,
    status: "failed",
    args: { command: "pnpm --dir desktop test -- --runInBand" },
    result: "Unknown option: --runInBand",
    isError: true,
    timestamp: timestamp(19),
    startedAt: timestamp(19),
    completedAt: timestamp(20),
    acpSource: "tool_call_update",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:suppressed-tool",
    type: "tool",
    renderClass: "suppressed",
    descriptor: descriptor(
      "suppressed",
      "Checked todos",
      null,
      "suppressed:stop-hook",
      {
        operation: "stop_hook",
        source: "harness",
      },
    ),
    title: "Stop hook",
    toolName: "stop",
    buzzToolName: null,
    status: "completed",
    args: {},
    result: "No open todos.",
    isError: false,
    timestamp: timestamp(21),
    startedAt: timestamp(21),
    completedAt: timestamp(21.4),
    acpSource: "tool_call_update",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:raw-rail",
    type: "metadata",
    renderClass: "raw-rail",
    title: "Raw ACP payload",
    sections: [
      {
        title: "tool_call_update",
        body: JSON.stringify(
          {
            sessionId,
            turnId,
            toolCallId: "debug:file-edit-tool",
            status: "completed",
            result: "Replaced 1 occurrence.",
          },
          null,
          2,
        ),
      },
    ],
    timestamp: timestamp(22),
    acpSource: "raw_json_rpc",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:error-lifecycle",
    type: "lifecycle",
    renderClass: "error",
    title: "Turn error recovered",
    text: "Retried with the supported desktop test command.",
    timestamp: timestamp(23),
    descriptor: descriptor(
      "error",
      "Turn error recovered",
      "unsupported test flag",
      "error:turn",
      {
        source: "acp",
      },
    ),
    acpSource: "turn_error",
    turnId,
    sessionId,
    channelId,
  },
  {
    id: "debug:assistant-message",
    type: "message",
    renderClass: "message",
    role: "assistant",
    title: "Agent",
    text: "Done — the Activity header now keeps Raw inside the settings cog, and the desktop gates are green.",
    timestamp: timestamp(25),
    acpSource: "agent_message_chunk",
    turnId,
    sessionId,
    channelId,
  },
];
